<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CabinetNC.Domain\CabinetNC.Domain.csproj" />
    <ProjectReference Include="..\CabinetNC.Domain.Compute\CabinetNC.Domain.Compute.csproj" />
    <ProjectReference Include="..\CabinetNC.Cloud.Contracts\CabinetNC.Cloud.Contracts.csproj" />
    <ProjectReference Include="..\CabinetNC.Cloud.NestContract\CabinetNC.Cloud.NestContract.csproj" />
  </ItemGroup>

</Project>
