# Generates UiLexicon.g.cs. Longer Chinese keys win at runtime.
from pathlib import Path

EXACT = {
    "打开方案…": "Open package…",
    "打开工程…": "Open project…",
    "保存工程": "Save project",
    "另存为": "Save as",
    "另存为…": "Save as…",
    "加入方案…": "Add package…",
    "加入方案": "Add package",
    "打开示例": "Open sample",
    "最近打开": "Recent",
    "（暂无）": "(none)",
    "退出": "Exit",
    "文件(_F)": "File(_F)",
    "编辑(_E)": "Edit(_E)",
    "视图(_V)": "View(_V)",
    "密排(_N)": "Nest(_N)",
    "刀路(_C)": "Toolpath(_C)",
    "导出(_X)": "Export(_X)",
    "帮助(_H)": "Help(_H)",
    "撤销": "Undo",
    "重做": "Redo",
    "复制": "Copy",
    "剪切": "Cut",
    "粘贴": "Paste",
    "删除": "Delete",
    "复制板件": "Copy part",
    "剪切板件": "Cut part",
    "粘贴板件": "Paste part",
    "删除整板": "Delete part",
    "镜像 X": "Mirror X",
    "镜像 Y": "Mirror Y",
    "镜像X": "Mirror X",
    "镜像Y": "Mirror Y",
    "创建板件…": "Create part…",
    "创建板件": "Create part",
    "编辑板件…": "Edit part…",
    "编辑板件": "Edit part",
    "适配大板": "Fit sheet",
    "放大": "Zoom in",
    "缩小": "Zoom out",
    "上一张大板": "Previous sheet",
    "下一张大板": "Next sheet",
    "1 载入方案": "1 Load package",
    "2 板材与设备": "2 Material & machine",
    "3 密排": "3 Nest",
    "4 刀路与加工档": "4 Toolpath",
    "5 导出": "5 Export",
    "初始密排": "First nest",
    "重新密排": "Nest again",
    "本张密排优化": "Optimize this sheet",
    "锁定摆位": "Lock placement",
    "计算当前板材": "Calculate this material",
    "计算全部": "Calculate all",
    "预检…": "Preflight…",
    "一键导出": "Export",
    "一键导出（Sheet×Tool 包）": "Export (sheet × tool)",
    "导出当前大板 .anc": "Export this sheet .anc",
    "导出当前板材种类 .anc": "Export this material .anc",
    "导出全部 .anc": "Export all .anc",
    "这张大板 DXF": "This sheet DXF",
    "按种类导出 DXF": "Export DXF by material",
    "工单 HTML…": "Job sheet HTML…",
    "快捷键": "Shortcuts",
    "使用日志…": "Usage log…",
    "使用日志": "Usage log",
    "关于 OmniCam…": "About OmniCam…",
    "关于 OmniCam": "About OmniCam",
    "切割站 · 生产加工": "Cut station · Production",
    "更多": "More",
    "就绪": "Ready",
    "取消": "Cancel",
    "确定": "OK",
    "关闭": "Close",
    "所有文件": "All files",
    "OmniCam 工程 (*.db)|*.db|所有文件|*.*": "OmniCam project (*.db)|*.db|All files|*.*",
    "生产加工": "Production",
    "补板库": "Recuts",
    "设备管理": "Machines",
    "路线管理": "Routes",
    "原料管理": "Materials",
    "工艺模版": "Templates",
    "参数设置": "Settings",
    "板材与设备": "Material & machine",
    "刀路与加工档": "Toolpath",
    "密排": "Nest",
    "刀路": "Toolpath",
    "导出": "Export",
    "载入": "Load",
    "板材": "Material",
    "方案": "Package",
    "工程": "Project",
    "板件": "Part",
    "大板": "Sheet",
    "余料": "Offcut",
    "预检": "Preflight",
    "打开目录": "Open folder",
    "上传到车间": "Upload to shop",
    "上传到车间…": "Upload to shop…",
    "车间云端": "Shop cloud",
    "刷新": "Refresh",
    "上传当前工程": "Upload this project",
    "上传时间": "Uploaded",
    "中文": "Chinese",
    "语言": "Language",
}

TERMS = [
    ("板材与设备", "Material & machine"),
    ("刀路与加工档", "Toolpath"),
    ("生产加工", "Production"),
    ("切割站", "Cut station"),
    ("补板库", "Recut library"),
    ("待补件", "recut part"),
    ("待补板件", "recut parts"),
    ("重新密排", "Nest again"),
    ("初始密排", "First nest"),
    ("一键导出", "Export"),
    ("本张密排优化", "Optimize this sheet"),
    ("锁定摆位", "Lock placement"),
    ("允许重叠", "Allow overlap"),
    ("允许90度旋转", "Allow 90° rotation"),
    ("允许旋转", "Allow rotation"),
    ("改变材料", "Change material"),
    ("改变纹路朝向", "Rotate grain"),
    ("合并材料", "Merge materials"),
    ("打开方案", "Open package"),
    ("打开工程", "Open project"),
    ("保存工程", "Save project"),
    ("加入方案", "Add package"),
    ("打开示例", "Open sample"),
    ("另存为", "Save as"),
    ("最近打开", "Recent"),
    ("创建板件", "Create part"),
    ("编辑板件", "Edit part"),
    ("复制板件", "Copy part"),
    ("剪切板件", "Cut part"),
    ("粘贴板件", "Paste part"),
    ("删除整板", "Delete part"),
    ("返回原方案", "Back to package"),
    ("补切密排", "Recut nest"),
    ("重新补切密排", "Recut nest again"),
    ("加入待补件", "Add recut part"),
    ("加入余料", "Add offcut"),
    ("清空余料", "Clear offcuts"),
    ("清空待补件", "Clear recut parts"),
    ("移除待补件", "Remove recut part"),
    ("移除余料", "Remove offcut"),
    ("添加余料", "Add offcut"),
    ("画余料", "Draw offcut"),
    ("手上余料", "Offcuts on hand"),
    ("前往板材与设备", "Go to material & machine"),
    ("前往密排", "Go to nest"),
    ("前往刀路", "Go to toolpath"),
    ("去密排页", "Go to nest"),
    ("去生产加工", "Go to production"),
    ("计算当前板材", "Calculate this material"),
    ("计算全部", "Calculate all"),
    ("计算引擎自检", "Compute engine check"),
    ("计算引擎", "Compute engine"),
    ("使用日志", "Usage log"),
    ("内部错误", "Internal error"),
    ("快捷键", "Shortcuts"),
    ("上机检查单", "Shop checklist"),
    ("设备管理", "Machines"),
    ("路线管理", "Routes"),
    ("原料管理", "Materials"),
    ("工艺模版", "Templates"),
    ("工艺模板", "Templates"),
    ("参数设置", "Settings"),
    ("参数库", "Settings library"),
    ("反推对照", "Reverse check"),
    ("重切勾选的板", "Recut selected parts"),
    ("重切板件", "Recut parts"),
    ("从 .anc 反推", "Reverse from .anc"),
    ("未保存的改动", "Unsaved changes"),
    ("排版校验通过", "Nest check passed"),
    ("排版校验失败", "Nest check failed"),
    ("预检通过", "Preflight passed"),
    ("预检失败", "Preflight failed"),
    ("预检未通过", "Preflight failed"),
    ("计码验算", "Shape check"),
    ("形状不符", "shape mismatch"),
    ("禁止导出", "export blocked"),
    ("禁止打包", "pack blocked"),
    ("写回方案", "Write back to package"),
    ("写回余料", "Write back offcut"),
    ("无法生成板件", "Cannot build the part"),
    ("无法生成余料", "Cannot build the offcut"),
    ("没有摆位", "No placement"),
    ("部分未排", "Some parts unplaced"),
    ("余料不够", "Not enough offcut"),
    ("待用区", "Holding bay"),
    ("板件待用区", "Part holding bay"),
    ("本张大板无摆位", "This sheet has no placement"),
    ("本张余料线", "Offcut lines on this sheet"),
    ("全部余料线", "Offcut lines on all sheets"),
    ("余料分割线", "Offcut split line"),
    ("余料切线", "offcut cut"),
    ("余料线", "offcut line"),
    ("余料外框", "Offcut outline"),
    ("新代开料包", "Syntec cut package"),
    ("新代开料", "Syntec cut"),
    ("新代", "Syntec"),
    ("贴标机", "Labeler"),
    ("贴标", "label"),
    ("标签锚点", "Label anchor"),
    ("标签图片", "label picture"),
    ("标签", "label"),
    ("工单", "job sheet"),
    ("刀路文件", "Toolpath files"),
    ("程序文件", "program file"),
    ("使用日志", "usage log"),
    ("构建信息", "Build info"),
    ("复制构建信息", "Copy build info"),
    ("出厂默认", "factory defaults"),
    ("车间材料库", "shop material library"),
    ("车间云端", "Shop cloud"),
    ("车间", "shop"),
    ("云端", "cloud"),
    ("上传当前工程", "Upload this project"),
    ("正在准备工程和新代开料包", "Preparing the project and Syntec cut package"),
    ("正在上传", "Uploading"),
    ("正在读取", "Reading"),
    ("已上传到车间", "Uploaded to the shop"),
    ("已上传", "Uploaded"),
    ("上传已取消", "Upload cancelled"),
    ("没有可上传的内容", "Nothing to upload"),
    ("没有可上传的新代程序", "No Syntec program to upload"),
    ("这台电脑还没有接上车间云端", "This computer is not connected to the shop cloud"),
    ("云端还没有工程", "No projects in the cloud"),
    ("云端没有返回上传地址", "The cloud did not return an upload address"),
    ("云端拒绝了这次上传", "The cloud rejected this upload"),
    ("云端要求的文件不在这包里", "A file the cloud asked for is not in this package"),
    ("车间云端配置读不了", "Cannot read the shop cloud settings"),
    ("这里是已经传到云端的工程", "Projects already sent to the cloud"),
    ("上传会带上当前工程", "Upload includes the current project"),
    ("以及算好的新代开料包", "and the Syntec cut package"),
    ("本地保存不会自动上传", "Saving locally does not upload"),
    ("检查没通过，没有上传", "Check failed, nothing uploaded"),
    ("刀路校验没通过，没有上传", "Toolpath check failed, nothing uploaded"),
    ("请先在机器列表里选择新代 E4 1330", "Select Syntec E4 1330 in the machine list first"),
    ("请先在「4 刀路与加工档」计算刀路，再上传", "Calculate the toolpath on step 4 before uploading"),
    ("请先载入方案", "Load a package first"),
    ("请先完成密排", "Finish the nest first"),
    ("请先计算刀路", "Calculate the toolpath first"),
    ("请选择材料", "Select a material"),
    ("请选择合并后的材料", "Select the material to merge into"),
    ("尚未载入方案", "No package loaded"),
    ("尚未载入", "Not loaded"),
    ("尚未密排", "Not nested"),
    ("尚未计算刀路", "Toolpath not calculated"),
    ("尚未排版", "Not nested"),
    ("尚未生成密排", "No nest yet"),
    ("尚无程序文件", "No program file yet"),
    ("方案已载入", "Package loaded"),
    ("板材参数可用", "Material settings ready"),
    ("密排完成", "Nest finished"),
    ("刀路已计算", "Toolpath calculated"),
    ("程序文件就绪", "Program file ready"),
    ("板件已修改，需要重新密排", "Parts changed, nest again"),
    ("板件已修改，之前的密排与刀路已作废", "Parts changed. The previous nest and toolpath are out of date"),
    ("导出前需要重新密排并生成刀路", "Nest again and rebuild the toolpath before export"),
    ("一键导出需要先完成密排和刀路", "Nest and build the toolpath before export"),
    ("没有可保存的 NC", "No NC to save"),
    ("无方案", "No package"),
    ("无包可导出", "No package to export"),
    ("无 NC", "No NC"),
    ("需要方案 + 密排", "Need a package and a nest"),
    ("先生成加工档", "Build the toolpath first"),
    ("打开方案或示例开始", "Open a package or the sample to start"),
    ("载入方案", "Load package"),
    ("选中板件可在右侧检视和编辑", "Select a part to inspect and edit it on the right"),
    ("参数库已从备份恢复", "Settings restored from backup"),
    ("参数库已重置为出厂默认", "Settings reset to factory defaults"),
    ("library.json 无法读取", "library.json could not be read"),
    ("可能是上次写入时断电", "the last save may have been cut off"),
    ("已改用上一份完整备份", "Using the last good backup"),
    ("请核对补板库和贴标目录", "Check the recut library and the label folder"),
    ("library.json 损坏且没有可用备份", "library.json is damaged and there is no backup"),
    ("补板库、材料和贴标目录需要重新录入", "Enter the recut library, materials, and label folder again"),
    ("OmniCam 遇到内部错误，这一步没有完成；已写入使用日志", "OmniCam hit an internal error and this step did not finish. It was written to the usage log"),
    ("建议：先「保存工程」，再重启 OmniCam。若反复出现，把日志目录连同工程文件交给维护人员", "Save the project, then restart OmniCam. If it keeps happening, send the log folder and the project file to the person who maintains it"),
    ("未嵌入", "not embedded"),
    ("选择左侧板件编辑几何", "Select a part on the left to edit its geometry"),
    ("拖孔/槽端点/边手柄", "drag a hole, groove end, or edge handle"),
    ("木纹", "grain"),
    ("白点", "White Stipple"),
    ("森绿", "Forest Green"),
    ("金属白", "Metallic White"),
    ("亮白", "Gloss White"),
    ("通孔", "through hole"),
    ("盲孔", "blind hole"),
    ("半槽", "tongue groove"),
    ("清底", "clearance"),
    ("开窗", "cutout"),
    ("口袋", "pocket"),
    ("铰链孔", "hinge hole"),
    ("铰杯", "hinge cup"),
    ("铰链", "hinge"),
    ("外形", "profile"),
    ("外框", "outline"),
    ("轮廓", "outline"),
    ("特征", "feature"),
    ("辅助线", "guide"),
    ("未分类槽", "unclassified groove"),
    ("宽槽", "wide groove"),
    ("插 tongue", "tongue"),
    ("留皮", "skin"),
    ("切穿", "through-cut"),
    ("贯通", "through"),
    ("通切", "through-cut"),
    ("下刀", "plunge"),
    ("进给", "feed"),
    ("转速", "spindle"),
    ("钻孔", "drill"),
    ("钻头", "drill"),
    ("刀径", "tool diameter"),
    ("刀具绑定", "tool link"),
    ("刀具库", "tool library"),
    ("刀具", "tool"),
    ("刀位", "tool position"),
    ("刀位点", "tool point"),
    ("安全高", "safe Z"),
    ("板厚", "thickness"),
    ("板底", "board bottom"),
    ("板面", "board face"),
    ("板宽", "sheet width"),
    ("板长", "sheet length"),
    ("大板尺寸", "sheet size"),
    ("大板边距", "sheet margin"),
    ("大板木纹", "sheet grain"),
    ("大板纹理", "sheet grain"),
    ("板件纹理", "part grain"),
    ("板件木纹", "part grain"),
    ("纹路朝向", "grain direction"),
    ("纹路", "grain"),
    ("纹理", "grain"),
    ("间距", "gap"),
    ("边距", "margin"),
    ("边缘距离", "edge margin"),
    ("边缘", "edge"),
    ("最短边", "shortest side"),
    ("利用率", "utilization"),
    ("未排", "unplaced"),
    ("已排", "placed"),
    ("摆位", "placement"),
    ("待用区", "holding bay"),
    ("待用", "holding"),
    ("冲突", "clash"),
    ("重叠", "overlap"),
    ("吸附", "snap"),
    ("锁定", "Lock"),
    ("解锁", "Unlock"),
    ("已锁定", "Locked"),
    ("已解锁", "Unlocked"),
    ("手摆", "hand placed"),
    ("原点", "origin"),
    ("贴原点", "against the origin"),
    ("左下角", "lower left"),
    ("右下角", "lower right"),
    ("材料不符", "Wrong material"),
    ("材料不匹配", "Material does not match"),
    ("材料未定", "Material not set"),
    ("未定材料", "unset material"),
    ("当前材料", "current material"),
    ("同材料", "the same material"),
    ("种类", "group"),
    ("重命名种类", "Rename group"),
    ("移出这份方案", "Remove this package"),
    ("移出方案", "Remove package"),
    ("参照板", "reference part"),
    ("参照板件", "reference part"),
    ("创建待补件", "Create recut part"),
    ("编辑余料", "Edit offcut"),
    ("写回", "Write back"),
    ("加入", "Add"),
    ("返回", "Back"),
    ("前往", "Go to"),
    ("进入", "Enter"),
    ("退出", "Exit"),
    ("切换", "Switch"),
    ("应用到生产加工", "Apply to production"),
    ("进入生产加工", "Enter production"),
    ("恢复默认", "Restore defaults"),
    ("保存参数", "Save settings"),
    ("保存库", "Save library"),
    ("添加材料", "Add material"),
    ("删除选中库材料", "Delete selected library material"),
    ("从方案同步材料", "Sync materials from the package"),
    ("添加刀具", "Add tool"),
    ("添加 / 更新刀具", "Add / update tool"),
    ("应用选中到当前加工", "Apply selection to this job"),
    ("删除选中", "Delete selected"),
    ("从机型重置刀具", "Reset tools from the machine"),
    ("当前机型", "Current machine"),
    ("当前作业工序", "Current operations"),
    ("工序开关", "Operation switches"),
    ("作业进度", "job progress"),
    ("机型目录", "machine list"),
    ("后置", "post"),
    ("机型", "machine"),
    ("机床", "machine"),
    ("排版默认值", "Nest defaults"),
    ("排版方式", "Nest method"),
    ("排版结果", "Nest result"),
    ("推荐精排", "Accurate nest (good for odd shapes)"),
    ("快速矩形", "Fast rectangles"),
    ("实验预览", "Experimental preview"),
    ("精排", "Accurate nest"),
    ("多边形间距校验", "Polygon gap check"),
    ("默认允许旋转排版", "Allow rotation by default"),
    ("默认允许旋转", "Allow rotation by default"),
    ("默认板宽", "Default sheet width"),
    ("默认板长", "Default sheet length"),
    ("默认间距", "Default gap"),
    ("默认边距", "Default margin"),
    ("默认", "default"),
    ("高级", "Advanced"),
    ("手动模式", "Manual mode"),
    ("手动", "manual"),
    ("自动计算", "Calculate automatically"),
    ("批量自动", "Auto all sheets"),
    ("自动", "auto"),
    ("清空本页", "Clear this sheet"),
    ("删除桥", "Delete bridge"),
    ("已有桥", "bridge already here"),
    ("成对", "paired"),
    ("座桥", "bridges"),
    ("三桥", "three bridges"),
    ("两桥", "two bridges"),
    ("桥心", "bridge core"),
    ("桥的宽度", "Bridge width"),
    ("桥", "bridge"),
    ("结束回原点", "Return home at end"),
    ("第一刀", "First pass"),
    ("第二刀", "Second pass"),
    ("最后一刀", "last pass"),
    ("下探深度", "Plunge depth"),
    ("贯通下探", "Through plunge"),
    ("探底深度", "Cut depth"),
    ("余料厚度", "Skin thickness"),
    ("最大钻孔直径", "Max drill diameter"),
    ("大刀最短边", "Large-tool minimum side"),
    ("条子长宽比", "Strip aspect ratio"),
    ("长宽比", "aspect ratio"),
    ("面积上限", "area limit"),
    ("斜下刀", "ramped plunge"),
    ("由里向外", "inside out"),
    ("螺旋", "spiral"),
    ("不跟半槽", "not the tongue feed"),
    ("孔径", "hole diameter"),
    ("槽宽", "groove width"),
    ("槽深", "groove depth"),
    ("槽端", "groove end"),
    ("槽段", "groove segment"),
    ("槽层", "groove layer"),
    ("外接矩形", "bounding box"),
    ("短边", "short side"),
    ("长条", "strip"),
    ("窄条", "narrow strip"),
    ("竖条", "vertical strip"),
    ("方料", "rectangle"),
    ("竖切", "vertical cut"),
    ("横切", "horizontal cut"),
    ("套裁", "parts-in-part"),
    ("居中", "center"),
    ("进中", "move inward"),
    ("整列", "as a column"),
    ("贴边", "against the edge"),
    ("锯开", "sawn"),
    ("外沿", "outer edge"),
    ("空洞", "opening"),
    ("嵌套", "nest inside"),
    ("零件", "part"),
    ("子件", "child part"),
    ("异形", "odd shape"),
    ("矩形", "rectangle"),
    ("多段线", "polyline"),
    ("角点", "corner"),
    ("圆心", "center"),
    ("半径", "radius"),
    ("直径", "diameter"),
    ("角度", "angle"),
    ("网格捕捉", "Grid snap"),
    ("网格", "grid"),
    ("正交", "Ortho"),
    ("捕捉", "snap"),
    ("命令", "Command"),
    ("选择对象", "Select objects"),
    ("点选", "click"),
    ("框选", "window select"),
    ("全选", "Select all"),
    ("特征号", "feature id"),
    ("指定基点", "Specify base point"),
    ("指定第二点", "Specify second point"),
    ("指定第一点", "Specify first point"),
    ("指定下一点", "Specify next point"),
    ("相对", "relative"),
    ("带符号", "signed"),
    ("闭合成板", "close the outline"),
    ("闭合", "close"),
    ("开链", "open chain"),
    ("切角", "notch"),
    ("修剪", "Trim"),
    ("延伸", "Extend"),
    ("画线", "Draw line"),
    ("画板", "drawing"),
    ("画布", "canvas"),
    ("空白画布", "blank canvas"),
    ("模型空间", "Model space"),
    ("毫米", "mm"),
    ("滚轮缩放", "wheel zoom"),
    ("滚轮", "wheel"),
    ("中键平移", "middle-button pan"),
    ("中键拖动", "middle-button drag"),
    ("中键", "middle button"),
    ("左键拖动", "left-button drag"),
    ("左键", "left button"),
    ("右键", "right-click"),
    ("双击", "double-click"),
    ("平移", "pan"),
    ("缩放", "zoom"),
    ("视口", "View"),
    ("仿真", "Simulation"),
    ("播放", "Play"),
    ("暂停", "Pause"),
    ("快移", "rapid"),
    ("空程", "rapid"),
    ("线宽", "width"),
    ("刀径", "tool diameter"),
    ("回到开头", "Go to start"),
    ("跳到结尾", "Go to end"),
    ("上一段", "Previous move"),
    ("下一段", "Next move"),
    ("运动块", "move"),
    ("运动", "move"),
    ("执行到", "at line"),
    ("点任意行可定位", "click a line to jump"),
    ("适配整张大板", "Fit the sheet"),
    ("适配", "Fit"),
    ("检视", "Inspect"),
    ("未选特征", "No feature selected"),
    ("应用特征参数", "Apply feature"),
    ("删特征", "Delete feature"),
    ("复制板", "Copy part"),
    ("旋转90°", "Rotate 90°"),
    ("旋转 90°", "Rotate 90°"),
    ("显示 / 隐藏图层", "Show / hide layers"),
    ("显示", "Show"),
    ("隐藏", "Hide"),
    ("选中", "Selected"),
    ("多选", "multi-select"),
    ("连选", "range select"),
    ("告警", "Warning"),
    ("警告", "Warning"),
    ("错误", "Error"),
    ("失败", "failed"),
    ("成功", "succeeded"),
    ("完成", "done"),
    ("通过", "passed"),
    ("就绪", "Ready"),
    ("取消", "Cancel"),
    ("确定", "OK"),
    ("关闭", "Close"),
    ("合并", "Merge"),
    ("应用", "Apply"),
    ("恢复", "Restore"),
    ("重置", "Reset"),
    ("刷新", "Refresh"),
    ("上传", "Upload"),
    ("下载", "Download"),
    ("导出", "Export"),
    ("导入", "Import"),
    ("打开", "Open"),
    ("保存", "Save"),
    ("删除", "Delete"),
    ("复制", "Copy"),
    ("剪切", "Cut"),
    ("粘贴", "Paste"),
    ("撤销", "Undo"),
    ("重做", "Redo"),
    ("创建", "Create"),
    ("编辑", "Edit"),
    ("移动", "Move"),
    ("旋转", "Rotate"),
    ("镜像", "Mirror"),
    ("移除", "Remove"),
    ("清空", "Clear"),
    ("添加", "Add"),
    ("计算", "Calculate"),
    ("校验", "Check"),
    ("验算", "verify"),
    ("预检", "Preflight"),
    ("检查", "Check"),
    ("选择", "Select"),
    ("重命名", "Rename"),
    ("文件", "File"),
    ("帮助", "Help"),
    ("关于", "About"),
    ("更多", "More"),
    ("诊断", "Diagnostics"),
    ("示例", "Sample"),
    ("导航", "Go to"),
    ("视图", "View"),
    ("工程名", "Project name"),
    ("工程", "project"),
    ("方案", "package"),
    ("板件", "part"),
    ("大板", "sheet"),
    ("小板", "small part"),
    ("整板", "full sheet"),
    ("空大板", "empty sheet"),
    ("板材", "material"),
    ("材料", "material"),
    ("余料", "offcut"),
    ("补切", "recut"),
    ("密排", "nest"),
    ("排版", "nest"),
    ("刀路", "toolpath"),
    ("孔", "hole"),
    ("槽", "groove"),
    ("刀", "tool"),
    ("板", "board"),
    ("件", "pc"),
    ("张", "sheet"),
    ("块", "pc"),
    ("个", ""),
    ("条", ""),
    ("次", ""),
    ("处", "place"),
    ("层", "layer"),
    ("边", "edge"),
    ("深", "depth"),
    ("宽", "width"),
    ("长", "length"),
    ("高", "height"),
    ("厚", "thickness"),
    ("线", "line"),
    ("点", "point"),
    ("面", "face"),
    ("号", "no."),
    ("步", "step"),
    ("页", "page"),
    ("种", "kind"),
    ("份", ""),
    ("单", "job"),
    ("包", "package"),
    ("档", "file"),
    ("库", "library"),
    ("名", "name"),
    ("值", "value"),
    ("类", "type"),
    ("向", "direction"),
    ("轴", "axis"),
    ("角", "corner"),
    ("圆", "circle"),
    ("方", "rect"),
    ("内", "inside"),
    ("外", "outside"),
    ("上", "up"),
    ("下", "down"),
    ("左", "left"),
    ("右", "right"),
    ("中", "middle"),
    ("新", "new"),
    ("旧", "old"),
    ("大", "large"),
    ("小", "small"),
    ("全", "all"),
    ("每", "each"),
    ("本", "this"),
    ("该", "this"),
    ("此", "this"),
    ("各", "each"),
    ("共", "total"),
    ("约", "about"),
    ("第", ""),
    ("其", "its"),
    ("等", "etc."),
    ("及", "and"),
    ("或", "or"),
    ("与", "and"),
    ("和", "and"),
    ("并", "and"),
    ("但", "but"),
    ("而", "and"),
    ("如", "if"),
    ("若", "if"),
    ("则", "then"),
    ("因", "because"),
    ("请", "Please"),
    ("先", "first"),
    ("再", "then"),
    ("又", "again"),
    ("也", "also"),
    ("都", "all"),
    ("只", "only"),
    ("还", "still"),
    ("更", "more"),
    ("已", "already"),
    ("未", "not"),
    ("不", "not"),
    ("没", "no"),
    ("非", "non"),
    ("无", "none"),
    ("有", "has"),
    ("是", "yes"),
    ("否", "no"),
    ("会", "will"),
    ("能", "can"),
    ("可", "can"),
    ("要", "need"),
    ("需", "need"),
    ("让", "let"),
    ("把", ""),
    ("将", ""),
    ("从", "from"),
    ("到", "to"),
    ("在", "in"),
    ("对", "for"),
    ("给", "for"),
    ("按", "by"),
    ("为", "as"),
    ("以", "by"),
    ("向", "toward"),
    ("至", "to"),
    ("后", "after"),
    ("前", "before"),
    ("的", ""),
    ("了", ""),
    ("地", ""),
    ("得", ""),
    ("着", ""),
    ("过", ""),
    ("来", ""),
    ("去", "go"),
    ("出", "out"),
    ("入", "in"),
    ("进", "in"),
    ("回", "back"),
    ("开", "open"),
    ("关", "close"),
    ("切", "cut"),
    ("排", "nest"),
    ("选", "select"),
    ("改", "change"),
    ("设", "set"),
    ("加", "add"),
    ("减", "subtract"),
    ("删", "delete"),
    ("存", "save"),
    ("用", "use"),
    ("看", "view"),
    ("放", "place"),
    ("拖", "drag"),
    ("按", "press"),
    ("其他", "Other"),
    ("其它", "Other"),
    ("当前", "current"),
    ("全部", "all"),
    ("部分", "some"),
    ("同一", "same"),
    ("不同", "different"),
    ("任意", "any"),
    ("指定", "specified"),
    ("一起", "together"),
    ("仍然", "still"),
    ("已经", "already"),
    ("正在", ""),
    ("尚未", "not yet"),
    ("无法", "Cannot"),
    ("不能", "Cannot"),
    ("不要", "Don't"),
    ("不会", "won't"),
    ("没有", "no"),
    ("不是", "not"),
    ("可以", "can"),
    ("必须", "must"),
    ("需要", "need"),
    ("应该", "should"),
    ("允许", "Allow"),
    ("禁止", "blocked"),
    ("跳过", "skip"),
    ("保留", "keep"),
    ("去掉", "remove"),
    ("清除", "clear"),
    ("生成", "build"),
    ("继续", "continue"),
    ("开始", "start"),
    ("结束", "end"),
    ("停止", "stop"),
    ("例如", "for example"),
    ("包括", "including"),
    ("至少", "at least"),
    ("直接", "directly"),
    ("单独", "separately"),
    ("批量", "batch"),
    ("注意", "Note"),
    ("建议", "Suggestion"),
    ("规则", "Rule"),
    ("原因", "reason"),
    ("问题", "problem"),
    ("硬门", "hard gate"),
    ("硬错误", "hard error"),
    ("作废", "out of date"),
    ("失效", "out of date"),
    ("损坏", "damaged"),
    ("备份", "backup"),
    ("断电", "power loss"),
    ("日志", "log"),
    ("目录", "folder"),
    ("子目录", "subfolder"),
    ("路径", "path"),
    ("位置", "position"),
    ("坐标", "coordinate"),
    ("尺寸", "size"),
    ("宽度", "Width"),
    ("长度", "Length"),
    ("高度", "Height"),
    ("厚度", "Thickness"),
    ("深度", "Depth"),
    ("面积", "area"),
    ("数量", "qty"),
    ("名称", "Name"),
    ("编号", "Id"),
    ("类型", "Type"),
    ("类型提示", "Type hint"),
    ("状态", "status"),
    ("时间", "time"),
    ("摘要", "summary"),
    ("详情", "detail"),
    ("列表", "list"),
    ("选项", "option"),
    ("参数", "settings"),
    ("数值", "value"),
    ("输入", "input"),
    ("焦点", "focus"),
    ("输入框", "input box"),
    ("侧栏", "side bar"),
    ("画布", "canvas"),
    ("窗口", "window"),
    ("菜单", "menu"),
    ("按钮", "button"),
    ("分组", "group"),
    ("分区", "group"),
    ("进度", "progress"),
    ("结果", "result"),
    ("报告", "report"),
    ("对照", "compare"),
    ("归属", "assigned"),
    ("缺失", "missing"),
    ("缺少", "missing"),
    ("无效", "invalid"),
    ("超出", "past"),
    ("不匹配", "does not match"),
    ("找不到", "not found"),
    ("已取消", "Cancelled"),
    ("已导出", "Exported"),
    ("已写入", "Written"),
    ("已保存", "Saved"),
    ("已打开", "Opened"),
    ("已载入", "Loaded"),
    ("已计算", "Calculated"),
    ("已应用", "Applied"),
    ("已合并", "Merged"),
    ("已删除", "Deleted"),
    ("已添加", "Added"),
    ("已更新", "Updated"),
    ("已切换", "Switched"),
    ("已移动", "Moved"),
    ("已复制", "Copied"),
    ("已粘贴", "Pasted"),
    ("已移除", "Removed"),
    ("已加入", "Added"),
    ("已创建", "Created"),
    ("已放", "Placed"),
    ("已放回", "Put back"),
    ("已改", "Changed"),
    ("已画", "Drew"),
    ("已转", "Rotated"),
    ("已选", "Selected"),
    ("未通过", "failed"),
    ("未切", "not cut"),
    ("未保存", "unsaved"),
    ("未载入", "not loaded"),
    ("未移动", "not moved"),
    ("放不下", "does not fit"),
    ("不够", "not enough"),
    ("太小", "too small"),
    ("自交", "self-intersection"),
    ("水平", "horizontal"),
    ("竖直", "vertical"),
    ("直角", "right angle"),
    ("多边形", "polygon"),
    ("至少", "at least"),
    ("大于", "larger than"),
    ("小于", "smaller than"),
    ("等于", "equal to"),
    ("介于", "between"),
    ("优先", "prefer"),
    ("否则", "otherwise"),
    ("如果", "if"),
    ("因为", "because"),
    ("所以", "so"),
    ("但是", "but"),
    ("然后", "then"),
    ("并且", "and"),
    ("或者", "or"),
    ("以及", "and"),
    ("其中", "of which"),
    ("例如", "for example"),
    ("左右", "around"),
    ("上下", "up and down"),
    ("前后", "forward and back"),
    ("之内", "within"),
    ("之外", "outside"),
    ("之前", "before"),
    ("之后", "after"),
    ("以上", "above"),
    ("以下", "below"),
    ("原来", "original"),
    ("原方案", "original package"),
    ("原来的", "original"),
    ("一起排", "nest together"),
    ("一起保存", "saved with it"),
    ("不会删除", "is not deleted"),
    ("不会保存", "is not saved"),
    ("磁盘上", "on disk"),
    ("实物", "the real board"),
    ("设计师", "the designer"),
    ("维护人员", "the maintainer"),
    ("操作员", "operator"),
    ("上机", "on the machine"),
    ("补齐", "fill in"),
    ("一直等待", "keeps waiting"),
    ("子目录", "subfolder"),
    ("平铺", "flat"),
    ("复制到", "copy to"),
    ("写入", "write"),
    ("读不了", "cannot read"),
    ("不存在", "does not exist"),
    ("不支持", "not supported"),
    ("换一个位置", "try another folder"),
    ("当前工作仍在窗口里", "the job is still in the window"),
    ("关闭前保存吗", "Save before closing?"),
    ("先保存吗", "Save first?"),
    ("继续导出吗", "Continue export?"),
    ("继续编辑", "keep editing"),
    ("丢弃改动", "discard changes"),
    ("写回并关闭", "write back and close"),
    ("只改", "change only"),
    ("同时写到", "also write to"),
    ("同规格", "the same size"),
    ("还有", "still"),
    ("另有", "more"),
    ("暂无", "none"),
    ("空", "empty"),
    ("（空）", "(empty)"),
    ("（通）", "(through)"),
    ("（未切）", "(not cut)"),
    ("暂存", "hold"),
    ("作废", "out of date"),
    ("微调", "nudge"),
    ("拖动", "drag"),
    ("拖回", "drag back"),
    ("拖进", "drag in"),
    ("松开放入", "release to drop"),
    ("松开放到最近空位", "release to the nearest free spot"),
    ("没有空位", "no free spot"),
    ("大于大板", "larger than the sheet"),
    ("可用区", "usable area"),
    ("仍留在待用区", "still in the holding bay"),
    ("仍在待用区", "still in the holding bay"),
    ("请拖到左侧大板上再松开", "Drag onto the sheet on the left, then release"),
    ("请拖到当前大板区域内再松开", "Drag inside the current sheet, then release"),
    ("切到同材料大板", "switch to a sheet of the same material"),
    ("再拖回", "then drag it back"),
    ("改完后", "after that"),
    ("可继续改其他板", "you can change other parts"),
    ("点「重新密排」", "click Nest again"),
    ("会作废", "will be out of date"),
    ("原密排不动", "the current nest stays"),
    ("切坏了，再切一块", "it was cut wrong, cut another"),
    ("还没切", "not cut yet"),
    ("整张大板", "the whole sheet"),
    ("按矩形收进", "store as a rectangle"),
    ("补切时先用它", "recut uses it first"),
    ("放不下再问要不要开整板", "if it does not fit, ask before opening a full sheet"),
    ("先用余料", "use offcuts first"),
    ("原方案的密排、刀路、导出会先暂存", "the package nest, toolpath, and export are set aside first"),
    ("原方案不动", "the package stays as it is"),
    ("跟这份工程一起保存", "saved with this project"),
    ("跟工程走", "stored with the project"),
    ("打开方案后", "After a package is open"),
    ("画出新外形", "draw a new outline"),
    ("选一块参照板", "pick a reference part"),
    ("材料跟当前选中的板", "material follows the selected part"),
    ("材料跟当前大板", "material follows the current sheet"),
    ("材料跟这块板", "material follows this part"),
    ("材料跟左边下拉", "material follows the list on the left"),
    ("不可改", "cannot be changed"),
    ("双击改名", "Double-click to rename"),
    ("双击改外形", "Double-click to edit the outline"),
    ("更多操作", "More"),
    ("尚未加载", "Not loaded"),
    ("从一份方案开始", "Start from a package"),
    ("会带你走完", "walks you through"),
    ("五步", "five steps"),
    ("也支持", "also accepts"),
    ("可多选", "you can select more than one"),
    ("并列密排", "nest them together"),
    ("写回当前工程文件", "Write the current project file"),
    ("还没有文件时再选位置", "if there is no file yet, pick a folder"),
    ("不覆盖当前文件", "does not overwrite the current file"),
    ("诊断与帮助", "Diagnostics and help"),
    ("问题排查", "troubleshooting"),
    ("光标在大板上的坐标", "Cursor position on the sheet"),
    ("当前缩放", "current zoom"),
    ("在本机计算", "calculated on this computer"),
    ("独立 Worker 进程", "the separate worker process"),
    ("停止本次密排，保留上一次结果", "Stop this nest and keep the previous result"),
    ("按 Sheet×Tool 导出", "Export by sheet and tool"),
    ("每张大板", "each sheet"),
    ("先载入", "Load"),
    ("放下补切", "Leave recut"),
    ("恢复进入补切前的密排、刀路和导出", "Restore the nest, toolpath, and export from before recut"),
    ("补切模式", "Recut"),
    ("这份工程的待补件与余料", "Recut parts and offcuts for this project"),
    ("机型目录与后置", "Machine list and posts"),
    ("工序开关与作业进度", "Operation switches and job progress"),
    ("刀具库与进给模板", "Tool library and feed presets"),
    ("排版默认值、机床标签目录", "Nest defaults and the machine label folder"),
    ("Ctrl 点选至少两个种类后，合并为其中一个材料", "Ctrl-click at least two groups, then merge them into one material"),
    ("打开空白画布，画出新外形后加入方案", "Open a blank canvas, draw a new outline, and add it to the package"),
    ("重命名种类 / 移出方案", "Rename a group / remove a package"),
    ("仿真时高亮当前执行行", "Highlight the running line during simulation"),
    ("点某一行可把仿真定位到该运动块", "Click a line to move the simulation there"),
    ("按当前大板材料创建，完成后进入右侧待用区", "Create from the current sheet material, then it goes to the holding bay"),
    ("给当前这种板材加一张空大板，排在这一组最后", "Add an empty sheet for this material, after the others in the group"),
    ("增加大板", "Add sheet"),
    ("右侧=待用区", "Right side = holding bay"),
    ("间距按板材种类", "Gap follows the material"),
    ("虚线空程", "dashed rapid"),
    ("橙=留", "orange = leave"),
    ("蓝=通切", "blue = through"),
    ("回到程序开头", "Back to the start of the program"),
    ("上一段运动", "Previous move"),
    ("下一段运动", "Next move"),
    ("播放 / 暂停", "Play / pause"),
    ("播放/暂停", "Play / pause"),
    ("跳到程序结尾", "Jump to the end of the program"),
    ("还没有可导出的刀路", "No toolpath to export yet"),
    ("刀路需要先有密排", "The toolpath needs a nest first"),
    ("刀路按大板上每块板的实际位置计算", "The toolpath uses each part's place on the sheet"),
    ("请先完成", "Finish"),
    ("再回到这里选机型并计算", "then come back, pick a machine, and calculate"),
    ("点「计算全部」生成刀路后", "After Calculate all builds the toolpath"),
    ("这里会按大板列出可导出的程序文件", "program files for each sheet are listed here"),
    ("打开 Fusion 导出的", "Open a Fusion export"),
    ("走完", "through"),
    ("快捷键：", "Shortcuts:"),
    ("切换步骤", "switch step"),
    ("缩小（−）", "Zoom out (−)"),
    ("放大（+）", "Zoom in (+)"),
    ("缩放 100%", "Zoom 100%"),
    ("选板后可编辑", "Select a part to edit"),
    ("打开简易 CAD", "Open the simple CAD"),
    ("也可菜单", "or use the menu"),
    ("或双击左侧板件", "or double-click a part on the left"),
    ("每种板材单独设大板尺寸", "Set the sheet size for each material"),
    ("载入方案后，这里会按板材种类列出参数框", "After a package is loaded, each material is listed here"),
    ("按当前各板材尺寸生成第一版密排，然后自动进入", "Build the first nest from the current sheet sizes, then open"),
    ("微调", "nudge"),
    ("种类名", "Group name"),
    ("板宽", "Sheet width"),
    ("板长", "Sheet length"),
    ("密排间距", "Nest gap"),
    ("边缘距离", "Edge margin"),
    ("Fusion 设定板件木纹", "Fusion sets the part grain"),
    ("这里设大板纹理方向", "Set the sheet grain direction here"),
    ("无纹理则不强制对齐", "With no grain, alignment is not forced"),
    ("默认收起", "Collapsed by default"),
    ("点开后可改单块板的木纹", "Expand to change one part's grain"),
    ("零件嵌套进另一零件的空洞", "Nest a part inside another part's opening"),
    ("引擎预留", "reserved in the engine"),
    ("勾选后写入本材料密排参数", "when checked, it is stored on this material"),
    ("打开后填余料", "When on, enter the offcut"),
    ("密排第一张用这块余料", "The first sheet of the nest is this offcut"),
    ("默认贴原点", "placed against the origin by default"),
    ("放不下再开整张大板", "if it does not fit, open a full sheet"),
    ("用右侧参数对全部大板重新排版", "Nest every sheet again with the settings on the right"),
    ("已锁定的摆位保留", "locked placements stay"),
    ("二次整理当前大板", "Tidy this sheet"),
    ("只把特别窄的条子", "only very narrow strips"),
    ("从宽度边缘整列调到中间", "are moved from the width edge to the middle"),
    ("宽的竖条贴边没问题，不动", "a wider vertical strip on the edge is fine and stays"),
    ("按当前大板排版", "From this sheet's nest"),
    ("外间隙生成余料", "build offcuts from the outer gap"),
    ("优先方料", "prefer a rectangle"),
    ("拆开会短于最短边则保留", "if a split would be shorter than the minimum side, keep"),
    ("按同样规则给每张已排大板生成余料线", "Build offcut lines for every nested sheet with the same rules"),
    ("下列为兼容旧逻辑的全局默认值", "These are old global defaults kept for compatibility"),
    ("正式排版以", "The real nest uses"),
    ("各材料为准", "each material"),
    ("尺寸 / 间距 / 边距以", "Size, gap, and margin come from"),
    ("各材料种类为准", "each material"),
    ("当前材料参数", "Current material"),
    ("未排 / 警告", "Unplaced / warnings"),
    ("只算当前大板，不重新密排", "This sheet only, do not nest again"),
    ("算全部大板，不重新密排", "All sheets, do not nest again"),
    ("完成后可进入", "then you can open"),
    ("可改", "can be changed"),
    ("留下的桥心宽度", "Width of the bridge core that stays"),
    ("刀心再加两个刀半径", "the tool center adds a tool radius on each side"),
    ("小于此面积的小板放", "parts smaller than this area get"),
    ("且在不同边", "on different edges"),
    ("介于两数之间放", "between the two numbers, place"),
    ("大于此面积算大板，不主动布", "larger than this counts as a big part and is not bridged automatically"),
    ("长/宽大于此值算长条", "length / width above this counts as a strip"),
    ("点外形刀路轨迹放桥", "Click the profile toolpath to place a bridge"),
    ("窄缝自动成对", "a narrow gap is paired automatically"),
    ("再点退出", "click again to leave"),
    ("点已有桥删除", "Click an existing bridge to delete it"),
    ("成对一起去掉", "a pair is removed together"),
    ("与手动模式不能同时开", "cannot be on together with manual mode"),
    ("当前大板：先小板长条，再纯长条，再补小板", "This sheet: small strips first, then plain strips, then the remaining small parts"),
    ("所有大板上每一块板都按自动规则布桥", "Every part on every sheet is bridged by the automatic rules"),
    ("缺刀路会先算全部", "if a toolpath is missing, all sheets are calculated first"),
    ("去掉当前板所有桥，其它页保留", "Remove every bridge on this sheet and keep the other sheets"),
    ("清底 / 其它槽", "Clearance / other grooves"),
    ("按短边自动选刀，不选手动刀号", "Pick the tool from the short side, not a manual tool number"),
    ("槽看槽宽，口袋看外接矩形短边", "Grooves use groove width. Pockets use the short side of the box"),
    ("直径", "Diameter"),
    ("的孔才钻孔", "holes are drilled only below this"),
    ("及以上", "and larger"),
    ("走清底", "go to clearance"),
    ("走", "use"),
    ("刀路默认螺旋由里向外", "The toolpath spirals from the inside out"),
    ("进给按清底", "Feed follows clearance"),
    ("只作用于通孔", "Through holes only"),
    ("盲孔深度跟特征，不在这里改", "Blind-hole depth follows the feature and is not changed here"),
    ("小于此值才钻孔", "Drill only below this"),
    ("等于或更大走清底", "this size or larger goes to clearance"),
    ("钻头只钻不铣", "The drill only drills, it does not mill"),
    ("不选手动刀号，孔径跟钻头走", "No manual tool number. Hole size follows the drill"),
    ("孔间", "between holes"),
    ("盲孔深度跟", "Blind-hole depth follows"),
    ("大于阈值的孔", "Holes above the limit"),
    ("含铰杯", "including hinge cups"),
    ("余料分割线贯通下探", "Through depth of the offcut split line"),
    ("导出当前大板", "Export this sheet"),
    ("导出当前板材种类", "Export this material"),
    ("导出选中文件同一板材种类的全部大板", "Export every sheet of the selected file's material"),
    ("例如全部", "for example all"),
    ("匣体", "carcass"),
    ("导出全部", "Export all"),
    ("导出所有大板的程序文件与标签", "Export program files and label bitmaps for every sheet"),
    ("到一个目录", "into one folder"),
    ("单独导出这张大板", "Export this sheet alone"),
    ("把当前选中的大板排版写成一份", "Write the selected sheet's nest to one"),
    ("给", "for"),
    ("演算", "to check"),
    ("按照种类导出", "Export by material"),
    ("同一板材种类的每张大板各一份", "one file for each sheet of that material"),
    ("这份工程要再切的板，和手上还能用的余料", "Parts to cut again, and offcuts you still have"),
    ("待补件可从密排页右键加入", "Add a recut part from the right-click menu on the nest"),
    ("或在这里创建板件", "or create a part here"),
    ("选一块参照板画出新外形", "pick a reference part and draw a new outline"),
    ("补切先排余料", "Recut nests offcuts first"),
    ("只排待补件", "Nest recut parts only"),
    ("放不下再问要不要加整板", "if they do not fit, ask before adding a full sheet"),
    ("原方案的密排、刀路、导出会先暂存", "the package nest, toolpath, and export are set aside first"),
    ("待补件和余料都跟这份工程一起保存", "Recut parts and offcuts are saved with this project"),
    ("先载入方案", "Load a package first"),
    ("补板库跟工程走", "The recut library is stored with the project"),
    ("打开方案后，可在这里", "After a package is open, you can"),
    ("或在密排页右键", "or right-click on the nest"),
    ("也可以把还没切的整张大板", "or take a sheet that has not been cut"),
    ("选方案里的一块板作为材料参照", "Pick a part in the package as the material reference"),
    ("在空白画布上画出新外形，加入待补件", "draw a new outline on a blank canvas and add it as a recut part"),
    ("移除选中的待补件", "Remove the selected recut part"),
    ("还没有待补件", "No recut parts yet"),
    ("点「创建板件」选一块参照板画出新外形", "Click Create part, pick a reference part, and draw a new outline"),
    ("或在密排页右键「加入待补件」", "or right-click Add recut part on the nest"),
    ("材料 / 厚度", "Material / thickness"),
    ("宽", "W"),
    ("长", "L"),
    ("按宽×长添加一块矩形余料", "Add a rectangular offcut from width × length"),
    ("打开画板，画直角余料外形", "Open the drawing and draw a right-angle offcut"),
    ("台阶", "step"),
    ("移除选中的余料", "Remove the selected offcut"),
    ("还没有余料", "No offcuts yet"),
    ("手填矩形", "type a rectangle"),
    ("或「画余料」画", "or Draw offcut for"),
    ("或在密排页右键「本张大板加入余料」", "or right-click Add this sheet as an offcut on the nest"),
    ("后置机型目录", "Post and machine list"),
    ("选中后用于", "The selection is used for"),
    ("输出", "output"),
    ("生产路线", "Production route"),
    ("下列为当前作业进度与机型工序开关", "Job progress and this machine's operation switches"),
    ("当前机型", "this machine"),
    ("半槽", "Tongue groove"),
    ("外形两刀", "Two profile passes"),
    ("当前作业工序摘要", "Operation summary"),
    ("车间材料库 + 当前方案板材", "Shop material library and this package's materials"),
    ("库持久化到", "The library is saved to"),
    ("板式", "board"),
    ("可按机型生成默认刀，并查看当前作业工序", "Build default tools for the machine and see this job's operations"),
    ("直径", "Diameter"),
    ("进给", "Feed"),
    ("转速", "Spindle"),
    ("排版默认值与车间偏好", "Nest defaults and shop preferences"),
    ("保存后写入", "After save, written to"),
    ("可一键应用到当前生产加工", "can be applied to the current job"),
    ("默认板宽", "Default sheet width"),
    ("默认间距", "Default gap"),
    ("默认板长", "Default sheet length"),
    ("默认边距", "Default margin"),
    ("机床与贴标", "Machine and labels"),
    ("导出的标签", "Exported label bitmaps"),
    ("必须直接放在贴标软件的", "must sit directly in the label software"),
    ("目录里", "folder"),
    ("不能有子目录", "no subfolder"),
    ("这里填机床电脑上的那个目录", "Enter that folder on the machine PC"),
    ("导出提示会照此显示", "the export message shows it"),
    ("现场默认", "Shop default"),
    ("事故复盘确认", "confirmed after the shop incident"),
    ("单文件后置", "single-file post"),
    ("垫板上表面", "top of the spoilboard"),
    ("穿透", "through"),
    ("每把刀", "each tool"),
    ("自动换刀", "automatic tool change"),
    ("这些数值在", "These values are on"),
    ("右侧可按作业调整", "on the right and can be changed per job"),
    ("板式家具切割站", "panel furniture cut station"),
    ("排版", "nest"),
    ("上机记录请抄这一段", "copy this block into the shop log"),
    ("每条记录都需要", "every record needs"),
    ("视口与密排快捷键在画布有焦点时生效", "View and nest shortcuts work when the canvas has focus"),
    ("输入框内不触发", "they do not fire inside an input box"),
    ("方案里已有的材料种类", "Material groups already in the package"),
    ("含厚度", "including thickness"),
    ("选哪一块板", "Which part"),
    ("只带它的材料，画布保持空白", "Only its material is used. The canvas stays blank"),
    ("画布是空的", "The canvas is empty"),
    ("画出新外形后加入待补件", "draw a new outline and add it as a recut part"),
    ("撤销上一步", "Undo"),
    ("把整块板放进视图", "Fit the whole part"),
    ("选择 · 点选 / 框选", "Select · click / window"),
    ("左→右全包，右→左相交", "left to right encloses, right to left crosses"),
    ("增减", "add or remove"),
    ("选对象", "select objects"),
    ("基点", "base point"),
    ("第二点", "second point"),
    ("可连续复制", "you can copy again"),
    ("删除选中的特征", "Delete the selected feature"),
    ("左边先选", "On the left, pick"),
    ("再画", "then draw"),
    ("问深度", "asks for depth"),
    ("闭合换轮廓、开链切角", "a closed chain replaces the outline, an open chain cuts a notch"),
    ("不进刀路", "not cut"),
    ("选切割边", "select cutting edges"),
    ("全部+外框", "all plus the outline"),
    ("点要剪掉的槽段或外框边", "click the groove segment or outline edge to trim"),
    ("选边界", "select boundaries"),
    ("点要延长的槽端", "click the groove end to extend"),
    ("外框不可选", "the outline cannot be selected"),
    ("通孔可改但写回后需重排", "through holes can be changed, but the nest must be rebuilt after write-back"),
    ("连续画线", "draw a chain"),
    ("拖动时", "while dragging"),
    ("输入相对", "enter a relative"),
    ("并锁定", "and lock it"),
    ("左键画矩形", "left button draws a rectangle"),
    ("右键切换角点/中心", "right button switches corner / center"),
    ("角点到角点", "Corner to corner"),
    ("中心到角点", "Center to corner"),
    ("默认圆心到边上", "center to edge by default"),
    ("右键切边上到边上", "right button switches to edge to edge"),
    ("圆心到边上", "Center to edge"),
    ("边上到边上", "Edge to edge"),
    ("板件本体 / 外框", "part body / outline"),
    ("不切透的槽 / 口袋 / 孔", "grooves, pockets, and holes that do not go through"),
    ("只作参考，不进刀路", "reference only, not cut"),
    ("右键可删除全部", "right-click to delete all"),
    ("删除所有辅助线", "Delete all guides"),
    ("密排创建：材料跟当前大板，不可改", "Created from the nest. Material follows this sheet and cannot be changed"),
    ("将板件改为", "Change parts to"),
    ("保持原数值", "Keep the numbers"),
    ("随厚度调整", "Scale with thickness"),
    ("通孔、通槽将按新厚度重写深度", "Through holes and through grooves get a new depth from the new thickness"),
    ("改完后可继续改其他板，再点「重新密排」", "You can change other parts, then click Nest again"),
    ("将选中的种类合并为", "Merge the selected groups into"),
    ("通孔、通槽将按新厚度重写深度", "Through holes and through grooves get a new depth from the new thickness"),
    ("仍要导出", "export anyway"),
    ("预检发现下列问题", "Preflight found these issues"),
    ("这些不是硬错误，可以强制导出", "These are not hard errors. You can export anyway"),
    ("但机床会按这份程序运动", "but the machine will run this program"),
    ("写下你为什么确认它是安全的", "Write why you are sure it is safe"),
    ("这段话会进入使用日志", "that note is stored in the usage log"),
    ("强制导出的原因", "Reason for exporting anyway"),
    ("至少 6 个字", "at least 6 characters"),
    ("槽深超出是设计要求，已与设计师确认", "the extra groove depth is intended and the designer confirmed it"),
    ("警告来自余料边，实物已核对", "the warning is the offcut edge and the board was checked"),
    ("记录原因并导出", "Save the reason and export"),
    ("导出后请在上机检查单里再核对一次", "After export, check the shop list once more"),
    ("全部特征 + 外框", "All features + outline"),
    ("无特征", "no features"),
    ("无已排工序", "No placed operations"),
    ("先密排并启用轮廓/钻孔/开槽", "Nest first and turn on profile, drill, and groove"),
    ("进给无效", "feed is invalid"),
    ("主轴转速未设置", "spindle speed is not set"),
    ("刀径为 0", "tool diameter is 0"),
    ("缺少刀具绑定", "missing tool link"),
    ("圆孔小于", "round holes under"),
    ("会用", "use"),
    ("钻孔", "drill"),
    ("更大的孔或口袋需要比刀径至少大", "a larger hole or pocket must be at least"),
    ("此处已有桥", "A bridge is already here"),
    ("请用删除桥去掉", "remove it with Delete bridge"),
    ("点外形刀路轨迹放桥", "Click the profile toolpath to place a bridge"),
    ("该板已有", "This part already has"),
    ("对面板已有", "The opposite part already has"),
    ("无法成对", "cannot pair"),
    ("已清空本页", "Cleared this sheet"),
    ("自动布桥", "Auto bridges"),
    ("全部自动布桥", "Auto bridges on all sheets"),
    ("无匹配板材", "No matching material"),
    ("组", "group"),
    ("内无法放入", "cannot place inside"),
    ("无法放入", "cannot place"),
    ("轮廓不足", "outline has too few points"),
    ("试排", "try"),
    ("完成", "done"),
    ("没有", "no"),
    ("的余料或整板", "offcut or full sheet"),
    ("的余料放不下", "offcut cannot fit"),
    ("密排优化", "Nest optimize"),
    ("窄条进中", "narrow strips inward"),
    ("套裁居中", "nested parts centered"),
    ("共移动", "moved"),
    ("外框开链与轮廓交了", "the open outline chain crosses the outline"),
    ("请画一条只穿过两次的线", "draw a line that crosses only twice"),
    ("最短边", "shortest side"),
    ("面积", "area"),
    ("切深", "cut depth"),
    ("槽深", "groove depth"),
    ("板厚", "thickness"),
    ("存在", "there are"),
    ("面工序", "face operations"),
    ("但未配置定位策略", "but no location strategy is set"),
    ("禁止导出反面程序", "the back-face program cannot be exported"),
    ("格式", "Format"),
    ("机型", "Machine"),
    ("已排", "placed"),
    ("未排", "unplaced"),
    ("利用率", "Utilization"),
    ("打印", "Print"),
    ("程序使用", "Program uses"),
    ("刀库无此刀径，无法扫掠", "the tool library has no tool of this diameter, so it cannot be swept"),
    ("无已排板件，验算跳过", "no placed parts, check skipped"),
    ("未验算", "not checked"),
    ("特征位于板外", "feature is outside the part"),
    ("外轮廓没有切穿", "the outside outline is not cut through"),
    ("无贯通刀路", "no through toolpath"),
    ("附近约", "about"),
    ("未切穿", "not cut through"),
    ("非声明桥位", "not a declared bridge"),
    ("完全没有贯通刀路", "has no through toolpath at all"),
    ("没有任何刀路到达", "no toolpath reaches it"),
    ("残留", "left"),
    ("最宽", "widest"),
    ("未清", "not cleared"),
    ("实切宽", "cut width"),
    ("直径不符", "diameter does not match"),
    ("钻深", "drill depth"),
    ("要求", "required"),
    ("圆心", "center"),
    ("最近下刀点偏", "nearest plunge is off by"),
    ("被切穿", "was cut through"),
    ("被切", "was cut"),
    ("无对应特征", "no matching feature"),
    ("刀路不属于任何板件", "toolpath is not on any part"),
    ("余料线或游走", "offcut line or a stray move"),
    ("最近特征", "nearest feature"),
    ("槽中心线", "groove centerline"),
    ("短于槽宽", "shorter than the groove width"),
    ("疑似轴互换", "axes may be swapped"),
    ("未知特征类型", "unknown feature type"),
    ("闭合外形没有归为板或开窗", "closed outlines were not classified as a part or a cutout"),
    ("不在任何板内", "not inside any part"),
    ("段运动", "moves"),
    ("闭合外形", "closed outlines"),
    ("需核对", "check this"),
    ("全部归属", "all assigned"),
    ("上机前对照原程序核对", "compare with the original program before cutting"),
    ("缺失的特征不会出现在重切件上", "missing features will not be on the recut part"),
    ("导出完成，但有", "Export finished, but"),
    ("个标签缺少", "labels are missing"),
    ("程序里的", "The program"),
    ("请求了不存在的标签图片", "asks for a label picture that is not there"),
    ("上机前补齐，否则机床会在", "Fill them in before cutting, or the machine stays at"),
    ("一直等待", "and waits"),
    ("张标签", "label bitmaps"),
    ("已平铺写入", "were written flat into"),
    ("全部复制到机床", "copy all of them to the machine"),
    ("不要放子目录", "do not put them in a subfolder"),
    ("已平铺写在同一目录", "were written flat in the same folder"),
    ("没有标签需要复制", "No labels to copy"),
    ("个程序文件", "program files"),
    ("个文件", "files"),
    ("个标签没有", "labels have no"),
    ("但程序请求的", "but the program asks for"),
    ("张在", "are in"),
    ("必须补齐", "must be filled in"),
    ("厚度", "Thickness"),
    ("可继续加纹理/双面等参数", "you can still add grain, double-side, and other settings"),
    ("第一张", "First sheet"),
    ("贴原点", "against the origin"),
    ("只落在外沿", "only on the outer edges"),
    ("无", "none"),
    ("单", "job"),
    ("块板", "parts"),
    ("块余料", "offcuts"),
    ("件待补", "to recut"),
    ("件已加入待补件", "added as recut parts"),
    ("已加入待补件", "Added as a recut part"),
    ("已加入余料", "Added as an offcut"),
    ("已经在余料里", "is already an offcut"),
    ("已移除余料", "Removed offcuts"),
    ("已移除待补件", "Removed recut parts"),
    ("已添加余料", "Added offcut"),
    ("已画余料", "Drew offcut"),
    ("已改余料", "Changed offcut"),
    ("已返回原方案", "Back to the package"),
    ("清空这份工程的", "Clear this project's"),
    ("余料已清空", "Offcuts cleared"),
    ("待补件已清空", "Recut parts cleared"),
    ("点「补切密排」一起排到余料上", "click Recut nest to place them on offcuts"),
    ("补切模式下的密排不会保存到工程", "The nest in recut mode is not saved in the project"),
    ("返回原方案再保存吗", "Go back to the package and then save?"),
    ("待补件和余料会一起保存", "Recut parts and offcuts are saved with it"),
    ("要各加一张整板再排吗", "Add one full sheet for each and nest again?"),
    ("放不下现有余料", "do not fit the offcuts you have"),
    ("用了", "Used"),
    ("张整板", "full sheets"),
    ("库存", "in stock"),
    ("块可用", "available"),
    ("未排", "unplaced"),
    ("拖动板件微调，右键改材料", "drag a part to nudge it, right-click to change material"),
    ("刀", "tools"),
    ("未写入", "not written"),
    ("每板一个", "one file per sheet"),
    ("贴标写在", "labels go in"),
    ("目录，不进程序", "folder, not in the program"),
    ("含自动换刀", "with automatic tool change"),
    ("标签 BMP 随程序一起写出", "label bitmaps are written with the program"),
    ("个文件", "files"),
    ("已导出新代开料包", "Exported the Syntec cut package"),
    ("张板", "sheets"),
    ("选择导出目录", "Choose the export folder"),
    ("选择位置，将按工程名创建文件夹", "Choose where to create a folder named after the project"),
    ("选择 DXF 导出目录", "Choose the DXF folder"),
    ("导出工单", "Export job sheet"),
    ("导出当前选中", "Export the selection"),
    ("打开方案：", "Open package:"),
    ("加入方案（可多选，与当前板件并列密排）", "Add packages (select more than one; they nest with the current parts)"),
    ("从机台 .anc / .nc 反推板件", "Rebuild parts from a machine .anc / .nc"),
    ("打开工程", "Open project"),
    ("单独导出这张大板 DXF", "Export this sheet as DXF"),
    ("导出 cut-package JSON", "Export cut-package JSON"),
    ("选择导出目录（保存此标记文件所在文件夹）", "Choose the export folder (save this marker in that folder)"),
    ("保存 NC", "Save NC"),
    ("已按种类导出", "Exported by material"),
    ("张大板 DXF", "sheet DXF files"),
    ("已导出工单", "Exported job sheet"),
    ("已导出 JSON", "Exported JSON"),
    ("已导出大板", "Exported sheet"),
    ("已保存 NC", "Saved NC"),
    ("已保存工程", "Saved project"),
    ("保存工程失败", "Could not save the project"),
    ("工程文件无法读取", "Could not read the project file"),
    ("已打开工程", "Opened project"),
    ("已打开", "Opened"),
    ("不支持的文件类型", "Unsupported file type"),
    ("文件已不存在", "File is gone"),
    ("当前工程", "The project"),
    ("有未保存的改动", "has unsaved changes"),
    ("前先保存吗", "Save before that?"),
    ("关闭前保存吗", "Save before closing?"),
    ("板件、密排或刀路", "parts, nest, or toolpath"),
    ("从", "From"),
    ("反推", "reversed"),
    ("勾选后点", "then click"),
    ("反推出", "Reversed"),
    ("补板", "Recut"),
    ("数量均为", "qty is"),
    ("确认板材后密排导出", "check the material, then nest and export"),
    ("已加入", "Added"),
    ("共", "total"),
    ("块板", "parts"),
    ("摆位", "placements"),
    ("刀路", "toolpath ops"),
    ("桥", "bridges"),
    ("工程名", "Project"),
    ("已恢复摆位", "placements restored"),
    ("文件", "File"),
    ("格式", "Format"),
    ("单位", "Units"),
    ("板件", "Parts"),
    ("板材规格", "Sheet sizes"),
    ("特征合计", "Features"),
    ("材料种类", "Materials"),
    ("警告", "Warnings"),
    ("另有", "and"),
    ("使用日志", "Usage log"),
    ("换一个位置再试", "try another folder"),
    ("刀路开关", "Toolpath switches"),
    ("还有", "Still"),
    ("块未上板", "parts are not on a sheet"),
    ("导出只会带已经摆上的板", "export includes only parts that are placed"),
    ("继续导出吗", "Continue export?"),
    ("一键打包完成", "Export package finished"),
    ("已写入", "Wrote"),
    ("每 Sheet×Tool 独立 NC", "one NC per sheet and tool"),
    ("每 Sheet 一份 DXF/manifest", "one DXF and manifest per sheet"),
    ("目录", "Folder"),
    ("一键打包成功", "Export package finished"),
    ("计算引擎自检通过", "Compute engine check passed"),
    ("独立 Worker 进程在线", "Worker process is online"),
    ("本机计算可用，独立 Worker 未运行", "Local calculation works. The separate worker is not running"),
    ("拖动", "Drag"),
    ("待用已选", "Holding selection"),
    ("加减", "add or remove"),
    ("拖进密排", "drag into the nest"),
    ("从待用区拖回", "Drag back from holding"),
    ("拖动中右键转90°", "right-click while dragging rotates 90°"),
    ("拖动中右键转", "right-click while dragging rotates"),
    ("上下左右", "one axis"),
    ("硬约束", "hard snap"),
    ("拖贴标", "Drag label"),
    ("已选", "Selected"),
    ("选中", "Selected"),
    ("已锁定", "Locked"),
    ("拖到左侧大板", "drag onto the sheet on the left"),
    ("当前大板是", "current sheet is"),
    ("大于大板可用区", "is larger than the usable sheet"),
    ("这张大板上没有空位", "No free spot on this sheet"),
    ("鼠标处有冲突", "The pointer is on a clash"),
    ("投影", "Preview"),
    ("已转纹路", "Grain rotated"),
    ("仍在待用区", "still in holding"),
    ("已入待用区", "moved to holding"),
    ("已复制", "Copied"),
    ("件到待用区", "parts to holding"),
    ("删除待用区", "Delete holding"),
    ("其中有从方案载入的板，删除后无法再排", "Some came from the package and cannot be nested again after delete"),
    ("已删除待用区", "Deleted from holding"),
    ("已改为", "Changed to"),
    ("可继续改其他板，改完后点「重新密排」", "You can change other parts, then click Nest again"),
    ("拖摆位", "Drag placement"),
    ("已移入待用区", "Moved to holding"),
    ("已移动", "Moved"),
    ("不能放回当前大板", "cannot go back on this sheet"),
    ("请先用", "Use"),
    ("切到同材料大板，再拖回", "switch to a sheet of the same material, then drag it back"),
    ("仍留在待用区", "left in holding"),
    ("已放回大板", "Put back on sheet"),
    ("贴标落点", "Label point"),
    ("显示失败", "could not draw"),
    ("切换到大板", "Switch to sheet"),
    ("库已保存", "Library saved"),
    ("已应用机型", "Machine applied"),
    ("已应用刀具", "Tool applied"),
    ("参数已保存", "Settings saved"),
    ("机床标签目录", "Machine label folder"),
    ("库材料", "Library materials"),
    ("尚未载入方案", "no package loaded"),
    ("已从方案同步", "Synced"),
    ("种材料到车间库", "materials from the package into the shop library"),
    ("车间库材料已是最新", "Shop library materials are already current"),
    ("无方案可同步", "No package to sync"),
    ("刀具", "Tools"),
    ("作业工序", "operations"),
    ("当前刀具", "Current tool"),
    ("库路径", "Library path"),
    ("示例方案载入失败", "Could not load the sample"),
    ("已载入示例", "Sample loaded"),
    ("块板", "parts"),
    ("已编辑", "Edited"),
    ("已失效", "out of date"),
    ("请回板材页「初始密排」", "go back to Material and click First nest"),
    ("特征右移", "Features moved right"),
    ("已加孔", "Hole added"),
    ("已加槽", "Groove added"),
    ("已删特征", "Feature deleted"),
    ("已删除板件", "Part deleted"),
    ("移出", "Remove"),
    ("及其", "and its"),
    ("密排和刀路会作废", "the nest and toolpath will be out of date"),
    ("磁盘上的", "The"),
    ("不会删除", "on disk is not deleted"),
    ("未找到方案", "Package not found"),
    ("已移出方案", "Package removed"),
    ("粘贴到待用区", "paste into holding"),
    ("已粘贴", "Pasted"),
    ("件到待用区", "parts into holding"),
    ("仍在大板", "still on sheet"),
    ("已复制为", "Copied as"),
    ("方案里还有", "The package also has"),
    ("块同规格板件", "parts of the same size"),
    ("是 = 改动同时写到这", "Yes = also write the change to these"),
    ("否 = 只改", "No = change only"),
    ("无改动", "no change"),
    ("外框/通孔已变", "outline or through holes changed"),
    ("外框/通孔已改，密排失效", "outline or through holes changed, the nest is out of date"),
    ("仅特征改动，密排保留", "features only, the nest stays"),
    ("刀路已重算", "toolpath recalculated"),
    ("仅特征改动", "features only"),
    ("已增加大板", "Sheet added"),
    ("创建板件后从待用区拖到这张板", "after you create a part, drag it from holding onto this sheet"),
    ("已创建", "Created"),
    ("在待用区", "in holding"),
    ("可拖回当前大板", "you can drag it onto the current sheet"),
    ("已加入板件", "Part added"),
    ("请确认板材后重新密排", "check the material, then nest again"),
    ("已合并为", "Merged into"),
    ("已启用 parts in part，但无合适开窗/子件可嵌套", "Parts in part is on, but nothing fits an opening"),
    ("件放入开窗空洞", "parts placed in openings"),
    ("有", ""),
    ("件没有排进大板", "parts were not placed on a sheet"),
    ("条警告，见右侧", "warnings, see"),
    ("右侧", "on the right"),
    ("小 板警告", "small-part warning"),
    ("小板警告", "Small-part warning"),
    ("已清除余料线", "Offcut lines cleared"),
    ("无合法余料线", "no valid offcut line"),
    ("余料边", "offcut edge"),
    ("或已铺满", "or the sheet is full"),
    ("当前大板没有可用的余料", "This sheet has no usable offcut"),
    ("距排版外包", "From the nest outline"),
    ("拆开后任一边", "if either side after a split is"),
    ("则改留", "keep"),
    ("均无合法余料", "have no valid offcut"),
    ("间隙", "gap"),
    ("张已生成", "sheets built"),
    ("张跳过", "sheets skipped"),
    ("发现", "Found"),
    ("处多边形/间距冲突", "polygon or gap clashes"),
    ("方式", "method"),
    ("件", "pc"),
    ("张板", "sheets"),
    ("切换到大板", "Could not switch to sheet"),
    ("上机检查单", "The shop checklist"),
    ("与后处理变更检查单在", "and the post-change checklist are in"),
    ("G-code · 点任意行可定位仿真", "G-code · click a line to move the simulation"),
    ("G-code · 执行到第", "G-code · at line"),
    ("行 · 点任意行可定位仿真", "· click a line to move the simulation"),
    ("线宽=刀径 · 滚轮缩放 · 中键平移 · F 适配", "line width = tool · wheel zoom · middle-button pan · F fits"),
    ("仿真", "Simulation"),
    ("缩放", "Zoom"),
    ("库", "Library"),
    ("方案", "package"),
    ("用", "use"),
    ("尚未", "not yet"),
    ("载入方案", "package loaded"),
    ("作业", "Job"),
    ("半槽", "tongue"),
    ("清底", "clearance"),
    ("外形", "profile"),
    ("钻孔", "drills"),
    ("当前大板", "Current sheet"),
    ("已计算全部大板", "Calculated all sheets"),
    ("已计算当前大板", "Calculated sheet"),
    ("大板", "Sheet"),
    ("全部余料线", "Offcut lines"),
    ("张已生成", "built"),
    ("张跳过", "skipped"),
    ("多边形/间距冲突", "polygon or gap clashes"),
    ("已载入示例", "Sample loaded"),
    ("工程=", "project="),
    ("材料=", "material="),
    ("画布拖拽编辑", "drag on the canvas to edit"),
    ("已编辑 · Nest/CAM 已失效", "Edited · nest and toolpath are out of date"),
    ("特征右移 10mm", "Features moved 10 mm"),
    ("旋转 90°", "Rotated 90°"),
    ("镜像 X", "Mirrored X"),
    ("镜像 Y", "Mirrored Y"),
    ("已加孔", "Hole added"),
    ("已加槽", "Groove added"),
    ("已删特征", "Deleted feature"),
    ("已删除板件", "Deleted part"),
    ("已复制", "Copied"),
    ("（Ctrl+V 粘贴到待用区）", "(Ctrl+V pastes into holding)"),
    ("（Ctrl+V 粘贴）", "(Ctrl+V pastes)"),
    ("已粘贴", "Pasted"),
    ("已增加大板", "Added sheet"),
    ("已创建", "Created"),
    ("已加入板件", "Added part"),
    ("已合并为", "Merged into"),
    ("已解锁摆位", "Placement unlocked"),
    ("已锁定摆位", "Placement locked"),
    ("parts in part：", "Parts in part:"),
    ("件放入开窗空洞", "parts placed in openings"),
    ("密排完成", "Nest finished"),
    ("张大板", "sheets"),
    ("未排", "unplaced"),
    ("件没有排进大板", "parts did not fit on a sheet"),
    ("条警告", "warnings"),
    ("见右侧「未排 / 警告」", "see Unplaced / warnings on the right"),
    ("已打开", "Opened"),
    ("文件已不存在", "The file is gone"),
    ("不支持的文件类型", "This file type is not supported"),
    ("已加入", "Added"),
    ("份", "packages"),
    ("从", "From"),
    ("反推", "reversed"),
    ("块板", "parts"),
    ("勾选后点「重切勾选的板」", "select them and click Recut selected parts"),
    ("反推出", "Reversed"),
    ("补板", "Recut parts"),
    ("数量均为 1", "qty is 1"),
    ("确认板材后密排导出", "check the material, then nest and export"),
    ("工程文件无法读取", "Could not read the project"),
    ("已打开工程", "Opened project"),
    ("保存工程失败", "Save failed"),
    ("已保存工程", "Project saved"),
    ("还有", "Still"),
    ("块未上板，导出只会带已经摆上的板", "parts are not on a sheet. Export includes only placed parts"),
    ("已导出大板", "Exported sheet"),
    ("已按种类导出", "Exported"),
    ("已导出工单", "Job sheet exported"),
    ("已导出 JSON", "JSON exported"),
    ("一键打包完成", "Package export finished"),
    ("已保存 NC", "NC saved"),
    ("拖动", "Dragging"),
    ("待用", "Holding"),
    ("从待用区拖回", "From holding"),
    ("拖贴标", "Dragging label"),
    ("材料不符", "Wrong material"),
    ("板件", "Part"),
    ("大于大板可用区", "is larger than the usable area"),
    ("这张大板上没有空位", "No room on this sheet"),
    ("鼠标处有冲突", "Clash under the pointer"),
    ("投影", "Preview"),
    ("松开放入", "release to drop"),
    ("已转纹路 90°", "Grain turned 90°"),
    ("已复制", "Copied"),
    ("件到待用区", "parts to holding"),
    ("删除待用区", "Delete"),
    ("件？", "parts?"),
    ("已删除待用区", "Deleted"),
    ("已改为", "Changed to"),
    ("拖动", "Dragging"),
    ("拖摆位", "Dragging"),
    ("旋转", "Rotate"),
    ("仍在待用区", "Still in holding"),
    ("请拖到当前大板区域内再松开", "Drag inside the current sheet, then let go"),
    ("已移入待用区", "Moved to holding"),
    ("已移动", "Moved"),
    ("材料不匹配，不能放回当前大板", "Wrong material, it cannot go back on this sheet"),
    ("请先用 ◀ ▶ 切到同材料大板，再拖回", "Use the arrows to open a sheet of the same material, then drag it back"),
    ("大于大板可用区", "larger than the usable area"),
    ("件仍留在待用区", "parts stay in holding"),
    ("已放回大板", "Put back on sheet"),
    ("贴标落点", "Label at"),
    ("显示失败", "could not draw"),
    ("有未保存的改动", "has unsaved changes"),
    ("关闭前保存吗", "Save before closing?"),
    ("编辑板件", "Edit part"),
    ("仅特征改动", "Features only"),
    ("写回后保留密排，只重算刀路", "after write-back the nest stays and only the toolpath is rebuilt"),
    ("可撤销", "undo"),
    ("通孔/外框已改", "Through holes or the outline changed"),
    ("写回后需重新密排", "the nest must be rebuilt after write-back"),
    ("指定", "Specify"),
    ("选择对象", "select objects"),
    ("点选 / 框选 / 输入特征号 / ALL", "click, window, feature id, or ALL"),
    ("已选", "selected"),
    ("继续", "continue"),
    ("指定基点", "base point"),
    ("点选，或", "click, or"),
    ("指定下一点", "next point"),
    ("回起点或", "back to the start or"),
    ("闭合成板", "close the outline"),
    ("退一点", "undo one point"),
    ("沿用", "keep"),
    ("指定槽深", "groove depth"),
    ("可写", "you can type"),
    ("深,宽", "depth,width"),
    ("指定第二点", "second point"),
    ("可连续复制", "you can copy again"),
    ("还没选对象", "nothing selected yet"),
    ("已添加辅助线", "Guide added"),
    ("不进刀路", "not cut"),
    ("继续画", "draw another"),
    ("完全重合", "lies exactly on"),
    ("已取消", "cancelled"),
    ("要改深度请选中它后重画", "to change depth, select it and draw it again"),
    ("要改长度用", "to change length use"),
    ("共线重叠，两条都会加工", "they overlap on one line and both will be cut"),
    ("外框", "outline"),
    ("已替换外框", "Outline replaced"),
    ("写回后需重排", "write-back needs a new nest"),
    ("已按这条线切开外框", "The outline was cut open along this line"),
    ("槽出板", "groove leaves the part"),
    ("已添加槽", "Groove added"),
    ("深", "depth"),
    ("宽", "width"),
    ("会出板", "would leave the part"),
    ("已删掉", "deleted"),
    ("剩余部分", "what was left"),
    ("再点一个，或", "click another, or"),
    ("结束", "finish"),
    ("已把", "split"),
    ("剪成", "into"),
    ("段", "pieces"),
    ("已剪短", "trimmed"),
    ("已延长", "extended"),
    ("到边界", "to the boundary"),
    ("会让", "would move"),
    ("已复制", "Copied"),
    ("个特征", "features"),
    ("指定下一个第二点，或", "pick the next second point, or"),
    ("已移动", "Moved"),
    ("已删除", "Deleted"),
    ("已撤销", "Undone"),
    ("还可撤销", "undo left"),
    ("步改动还没写回方案", "steps are not written back to the package"),
    ("是 = 写回并关闭", "Yes = write back and close"),
    ("否 = 丢弃改动", "No = discard"),
    ("取消 = 继续编辑", "Cancel = keep editing"),
    ("已删除", "Deleted"),
    ("条辅助线", "guides"),
    ("指定", "Specify"),
    ("深度", "depth"),
    ("槽可写", "for a groove you can type"),
    ("已锁定", "locked"),
    ("或", "or"),
    ("输入宽高", "type width and height"),
    ("输入", "type"),
    ("角度", "angle"),
    ("高", "height"),
    ("命令", "Command"),
    ("未知命令", "Unknown command"),
    ("全选", "select all"),
    ("不能延伸外框", "the outline cannot be extended"),
    ("要用", "use"),
    ("点外框边", "click an outline edge"),
    ("已改外框", "Outline changed"),
    ("先画直角外框", "Draw a right-angle outline first"),
    ("已开", "is on"),
    ("先画", "Draw"),
    ("外框", "the outline first"),
    ("至少", "at least"),
    ("点的多段线", "points"),
    ("缺少板件编号", "Part id is missing"),
    ("外框点数不足", "The outline needs more points"),
    ("余料外框至少", "The offcut outline needs at least"),
    ("个角", "corners"),
    ("直角多边形", "a right-angle polygon"),
    ("余料外框必须是直角边", "Offcut edges must be horizontal or vertical"),
    ("余料面积太小", "Offcut area is too small"),
    ("余料外框不能自交", "The offcut outline cannot cross itself"),
    ("余料宽/长须", "Offcut width and length must be"),
    ("板件轮廓不足", "Part outline needs"),
    ("个点", "points"),
    ("无匹配板材", "No material matches"),
    ("内 NFP 无法放入", "NFP cannot place it"),
    ("内无法放入", "cannot place it"),
    ("尺寸/缺陷/边距", "size, defect, or margin"),
    ("轮廓/边距/缺陷", "outline, margin, or a defect"),
    ("方", "Rect"),
    ("臂", "arm"),
    ("左余料", "offcut on the left"),
    ("右余料", "offcut on the right"),
    ("下余料", "offcut below"),
    ("上余料", "offcut above"),
    ("竖切", "Vertical cut"),
    ("横切", "Horizontal cut"),
    ("密排…", "Nesting…"),
    ("密排优化", "Nest optimize"),
    ("选机器", "pick a machine"),
    ("计算当前板或全部", "calculate this sheet or all"),
    ("点", "click"),
    ("查看参数", "to see settings"),
    ("左右翻大板", "step through sheets"),
    ("右键改材料", "right-click to change material"),
    ("拖摆位", "drag a placement"),
    ("相同板件已合并数量", "identical parts are grouped by quantity"),
    ("按材料设大板", "set the sheet per material"),
    ("点右侧刀路文件，左边看", "click a toolpath file on the right, read"),
    ("中间看该大板刀路", "and see that sheet's toolpath in the middle"),
    ("选中右侧程序文件，核对", "select a program on the right and check"),
    ("与仿真后导出", "and the simulation, then export"),
    ("这个文件不是可读的 OmniCam 工程", "This file is not a readable OmniCam project"),
    ("可能已损坏或复制不完整", "it may be damaged or the copy is incomplete"),
    ("板件已改", "Parts changed"),
    ("当前摆位仍可用", "the current placement can still be used"),
    ("手摆也算", "including parts you placed by hand"),
    ("导出会按摆位重算刀路", "export rebuilds the toolpath from the placement"),
    ("手摆或重排均可", "hand placement or a new nest both work"),
    ("导出会按当前摆位重算刀路", "export rebuilds the toolpath from the current placement"),
    ("导出 · 选中右侧程序文件，核对 G-code 与仿真后导出", "Export · select a program on the right, check the G-code and the simulation, then export"),
    ("未识别到危险窄条", "No dangerous narrow strip"),
    ("短边不够窄，或相对同列竖板不够细", "the short side is not narrow enough, or it is not thin next to the vertical parts in the same column"),
    ("画面右下角", "lower right of the screen"),
    ("程序 X 从右边量", "program X is measured from the right"),
    ("板尾原点", "origin at the end of the board"),
    ("板长从尾部量", "length is measured from the tail"),
    ("台面", "table"),
    ("未标", "not marked"),
    ("按槽宽选刀", "tool follows groove width"),
    ("点开可改成半槽", "open it to mark it as a tongue groove"),
    ("按短边选刀", "tool follows the short side"),
    ("过桥留", "leave"),
    ("深度跟板件特征", "depth follows the part feature"),
    ("清底/第一刀", "clearance / first pass"),
    ("最后一刀", "last pass"),
    ("下刀", "plunge"),
    ("安全高", "Safe Z"),
    ("外形留皮", "profile skin"),
    ("切深", "cut depth"),
    ("大于 板厚", "greater than thickness"),
    ("槽深", "groove depth"),
    ("存在 B 面工序", "There are back-face operations"),
    ("未配置定位策略", "no location strategy is set"),
    ("禁止导出反面程序", "the back program cannot be exported"),
    ("个刀位点超出板材", "tool points are outside the sheet"),
    ("缺少刀具绑定", "Missing tool link"),
    ("圆孔小于", "A round hole under"),
    ("会用 T3 钻孔", "is drilled with T3"),
    ("更大的孔或口袋需要比刀径至少大 1mm", "a larger hole or pocket must be at least 1 mm bigger than the tool"),
    ("该板已有", "This part already has"),
    ("个桥", "bridges"),
    ("无法成对", "so it cannot be paired"),
    ("已清空本页", "Cleared"),
    ("个桥", "bridges on this sheet"),
    ("自动布桥", "Placed"),
    ("全部自动布桥", "Placed"),
    ("张大板", "sheets"),
    ("块", "parts"),
    ("无匹配板材", "No material for"),
    ("试排", "try"),
    ("组", "Group"),
    ("内 NFP 无法放入", "NFP cannot place this group"),
    ("内无法放入（尺寸/缺陷/边距）", "cannot place this group (size, defect, or margin)"),
    ("内无法放入（轮廓/边距/缺陷）", "cannot place this group (outline, margin, or defect)"),
    ("完成", "done"),
    ("没有", "No"),
    ("的余料或整板", "offcut or full sheet for"),
    ("的余料放不下", "offcut cannot fit"),
    ("密排优化 · 窄条进中", "Nest optimize · narrow strips inward"),
    ("套裁居中", "parts-in-part centered"),
    ("共移动", "moved"),
    ("外框开链与轮廓交了", "The open outline crosses the profile"),
    ("次", "times"),
    ("请画一条只穿过两次的线", "Draw a line that crosses only twice"),
    ("最短边", "Shortest side"),
    ("面积", "Area"),
    ("程序", "Program"),
    ("段运动", "moves"),
    ("闭合外形", "closed outlines"),
    ("孔", "holes"),
    ("槽", "grooves"),
    ("口袋", "pockets"),
    ("开窗", "cutouts"),
    ("无特征", "no features"),
    ("个闭合外形没有归为板或开窗", "closed outlines were not a part or a cutout"),
    ("个孔/槽/口袋不在任何板内", "holes, grooves, or pockets are not inside a part"),
    ("上机前对照原程序核对，缺失的特征不会出现在重切件上", "Compare with the original program before cutting. Missing features will not be on the recut part"),
    ("需核对", "Needs a check"),
    ("全部归属", "All assigned"),
    ("反推对照", "Reverse check"),
    ("程序", "program"),
    ("导出完成，但有", "Export finished, but"),
    ("个标签缺少 BMP", "labels have no BMP"),
    ("没有标签需要复制", "No labels to copy"),
    ("已导出", "Exported"),
    ("个程序文件", "program files"),
    ("张标签 BMP 已平铺写在同一目录", "label BMPs were written flat in the same folder"),
    ("全部复制到机床", "Copy all of them to the machine"),
    ("不要放子目录", "Do not use a subfolder"),
    ("标签", "Labels"),
    ("张在", "are in"),
    ("但程序请求的", "but the program asks for"),
    ("个标签没有 BMP", "labels with no BMP"),
    ("上机前必须补齐，否则 M701 会一直等待", "Fill them in before cutting or M701 keeps waiting"),
    ("张已平铺写入", "were written flat to"),
    ("全部复制到机床", "copy all of them onto the machine"),
    ("准备上传失败", "Could not prepare the upload"),
    ("读云端列表失败", "Could not read the cloud list"),
    ("个工程", "projects"),
    ("正在读取云端工程", "Reading cloud projects"),
    ("正在向云端申请上传地址", "Asking the cloud for an upload address"),
    ("没有还原出板件", "No parts were rebuilt"),
    ("还没有大板上的摆位", "Nothing is placed on a sheet yet"),
    ("请密排，或把板拖到大板上后再导出", "Nest, or drag parts onto a sheet, then export"),
    ("密排间距/碰撞/混组硬门未通过，禁止导出", "Nest gap, clash, or mixed-group gate failed. Export is blocked"),
    ("预检硬错误，禁止导出", "Preflight hard error. Export is blocked"),
    ("计码验算未通过，禁止导出", "Shape check failed. Export is blocked"),
    ("G-code 与板件形状不符", "the G-code does not match the part shape"),
    ("已尝试自动收紧工艺仍未通过", "Automatic process tightening still failed"),
    ("验算不可跳过，请修正特征/刀具后重新计算", "The check cannot be skipped. Fix the feature or tool, then calculate again"),
    ("验算不可跳过", "The check cannot be skipped"),
    ("请修正特征/刀具后重新计算", "Fix the feature or tool, then calculate again"),
    ("已自动尝试", "Automatically tried"),
    ("轮工艺收紧仍未通过", "tightening passes and it still failed"),
    ("轮自动收紧工艺后通过", "tightening passes, then it passed"),
    ("禁止打包", "pack blocked"),
    ("第", "pass"),
    ("轮", ""),
    ("自动收紧工艺后通过", "after tightening the process"),
    ("未通过", "failed"),
    ("已阻止导出", "export blocked"),
    ("将", "Change"),
    ("件改为", "parts to"),
    ("（", ""),
    ("）", ""),
    ("件）", "parts)"),
    ("单", "jobs"),
    ("厚度", "Thickness"),
    ("可继续加纹理/双面等参数", "grain, double-side, and other settings can still be added"),
    ("板件木纹", "Part grain"),
    ("块 X", "on X"),
    ("块 Y", "on Y"),
    ("无）", "with none)"),
    ("第一张", "First sheet"),
    ("贴原点 · 大板边距只落在外沿", "against the origin · sheet margin only on the outer edges"),
    ("选中两块时按住", "with two parts selected, hold"),
    ("显示两块板的间距", "show the gap between them"),
    ("拖动中按住", "while dragging, hold"),
    ("锁定单轴移动", "lock to one axis"),
    ("吸附到相邻板件（按间距）", "snap to the next part (by the gap)"),
    ("拖到侧栏为暂存", "drag to the side bar to hold"),
    ("移动板件", "move a part"),
    ("播放 / 暂停（导出页）", "play / pause (export)"),
    ("刀位跳到该块", "the tool jumps to that block"),
    ("点击代码行", "Click a code line"),
    ("以指针为中心缩放", "zoom around the pointer"),
    ("适配整张大板", "fit the sheet"),
    ("放大 / 缩小", "zoom in / out"),
    ("或", "or"),
    ("数值框：提交 / 放弃", "number box: commit / cancel"),
    ("删除选中特征，否则删除选中板件", "delete the selected feature, otherwise delete the selected part"),
    ("复制 / 剪切 / 粘贴选中板件", "copy / cut / paste the selected part"),
    ("撤销 / 重做", "undo / redo"),
    ("跳到 载入 / 板材 / 密排 / 刀路 / 导出", "go to Load / Material / Nest / Toolpath / Export"),
    ("一键导出（需先完成密排与刀路）", "export (nest and toolpath first)"),
    ("保存工程（已有文件则直接写回）", "save the project (writes the file if it already exists)"),
    ("打开方案", "open package"),
    ("打开工程", "open project"),
    ("另存为", "save as"),
    ("中键拖动", "middle-button drag"),
    ("左键拖动", "left-button drag"),
    ("拖动中按右键", "right-click while dragging"),
    ("旋转 90°", "rotate 90°"),
    ("F 或 Home", "F or Home"),
    ("播放 / 暂停（空格）", "Play / pause (space)"),
    ("仿真快移线（导出页）", "Simulation rapids (export)"),
    ("孔 / 槽 / 口袋特征", "Holes / grooves / pockets"),
    ("选中板件尺寸标注", "Size of the selected part"),
    ("把这块板复制一件到补板库，原密排不动", "Copy this part into the recut library. The nest stays"),
    ("本张大板加入余料（还没切）", "Add this sheet as an offcut (not cut yet)"),
    ("整张大板按矩形收进补板库的余料，补切时先用它", "Store the whole sheet as a rectangular offcut. Recut uses it first"),
    ("加入待补件（切坏了，再切一块）", "Add recut part (it was cut wrong, cut another)"),
    ("再打开一份或多份 .cnjob，和当前板件并列密排", "Open one or more .cnjob files and nest them with the current parts"),
    ("在简易 CAD 里移动 / 复制 / 删除已选板的孔、槽、口袋", "Move, copy, or delete holes, grooves, and pockets in the simple CAD"),
    ("按板材与设备页的参数生成第一版密排", "Build the first nest from the Material & machine settings"),
    ("检查深度、顺序、刀具、定位等硬门", "Check depth, order, tools, and location gates"),
    ("工程名：保存工程默认用这个名字，导出 NC 也会带上", "Project name: Save uses this name, and exported NC includes it"),
    ("打开 Fusion 导出的 .cnjob / woodjob / cut-package　(Ctrl+O)", "Open a Fusion .cnjob / woodjob / cut-package (Ctrl+O)"),
    ("打开保存过的工程 (.db)　(Ctrl+Shift+O)", "Open a saved project (.db) (Ctrl+Shift+O)"),
    ("写回当前工程文件；还没有文件时再选位置　(Ctrl+S)", "Write the current project. If there is no file yet, pick a place (Ctrl+S)"),
    ("另存一份工程，不覆盖当前文件　(Ctrl+Shift+S)", "Save a copy without overwriting the current file (Ctrl+Shift+S)"),
    ("把当前工程和新代开料包传到车间云端。本地保存不会自动上传。", "Send this project and the Syntec cut package to the shop cloud. Saving locally does not upload."),
    ("打开 app_usage.jsonl / latest（问题排查）", "Open app_usage.jsonl / latest (troubleshooting)"),
    ("排版与刀路在本机计算。「更多 → 计算引擎自检」可检查独立 Worker 进程。", "Nest and toolpath are calculated on this computer. More → Compute engine check looks at the worker process."),
    ("载入 → 板材 → 密排 → 刀路 → 导出", "Load → Material → Nest → Toolpath → Export"),
    ("按 Sheet×Tool 导出 NC + 每张大板 DXF/manifest + BOM/标签　(Ctrl+E)", "Export NC by sheet and tool, plus a DXF and manifest per sheet, BOM, and labels (Ctrl+E)"),
    ("先载入 woodjob / cut-package 方案", "Load a woodjob / cut-package first"),
    ("G-code 切割仿真", "G-code cut simulation"),
    ("虚线空程 · 线宽=刀径 · 橙=留 0.5 · 蓝=通切", "Dashed rapid · line width = tool · orange = leave 0.5 · blue = through"),
    ("显示 / 隐藏图层：纹理、特征、标签、尺寸", "Show / hide: grain, features, labels, sizes"),
    ("显示 / 隐藏图层：快移线、标签、纹理", "Show / hide: rapids, labels, grain"),
    ("尚未生成密排", "No nest yet"),
    ("先到「2 板材与设备」确认每种板材的大板尺寸与间距，再点「初始密排」。", "On step 2, check each material's sheet size and gap, then click First nest."),
    ("刀路需要先有密排", "The toolpath needs a nest"),
    ("刀路按大板上每块板的实际位置计算。请先完成「3 密排」，再回到这里选机型并计算。", "The toolpath uses each part's place on the sheet. Finish step 3, then come back, pick a machine, and calculate."),
    ("还没有可导出的刀路", "Nothing to export yet"),
    ("到「4 刀路与加工档」点「计算全部」生成刀路后，这里会按大板列出可导出的程序文件。", "On step 4, click Calculate all. Program files for each sheet show up here."),
    ("从一份方案开始", "Start from a package"),
    ("打开 Fusion 导出的 .cnjob，OmniCam 会带你走完板材 → 密排 → 刀路 → 导出五步。也支持 woodjob / cut-package。", "Open a Fusion .cnjob. OmniCam walks you through material, nest, toolpath, and export. woodjob and cut-package work too."),
    ("快捷键：Ctrl+O 打开方案 · Ctrl+S 保存工程 · Ctrl+1…5 切换步骤", "Shortcuts: Ctrl+O open package · Ctrl+S save project · Ctrl+1…5 switch step"),
    ("适配整张大板（F / Home，双击中键）", "Fit the sheet (F / Home, double-click the middle button)"),
    ("打开简易 CAD：移动 / 复制 / 删除孔、槽、口袋。也可菜单 编辑 → 编辑板件，或双击左侧板件。", "Open the simple CAD to move, copy, or delete holes, grooves, and pockets. You can also use Edit → Edit part, or double-click a part."),
    ("X / 直径 mm", "X / diameter mm"),
    ("Y / 深度·宽度 mm", "Y / depth · width mm"),
    ("特征→10", "Features +10"),
    ("+孔⌀8", "+ hole ⌀8"),
    ("+槽", "+ groove"),
    ("检视 / 编辑", "Inspect / edit"),
    ("选板后可编辑", "Select a part to edit"),
    ("特征 Inspector", "Feature inspector"),
    ("复制板件 (Ctrl+C)", "Copy part (Ctrl+C)"),
    ("粘贴板件 (Ctrl+V)", "Paste part (Ctrl+V)"),
    ("剪切板件 (Ctrl+X)", "Cut part (Ctrl+X)"),
    ("删除特征 (Del)", "Delete feature (Del)"),
    ("复制 (Ctrl+C)", "Copy (Ctrl+C)"),
    ("粘贴 (Ctrl+V)", "Paste (Ctrl+V)"),
    ("剪切 (Ctrl+X)", "Cut (Ctrl+X)"),
    ("删除整板 (Del)", "Delete part (Del)"),
    ("Profiling · 外形 / 开窗 / 半槽", "Profiling · outline / cutout / tongue"),
    ("Area Clearance · 口袋 / 宽槽清底", "Area Clearance · pocket / wide groove"),
    ("Drilling · 孔", "Drilling · holes"),
    ("Guillotine cut · 界面二的余料分割线", "Guillotine cut · offcut split lines"),
    ("程序结束先 G0 X0 Y0 再 G80。默认开。", "End with G0 X0 Y0, then G80. On by default."),
    ("半槽 T1", "Tongue T1"),
    ("T1 半槽进给，可改。默认 9000。", "T1 tongue feed. Editable. Default 9000."),
    ("转速 (rpm)", "Spindle (rpm)"),
    ("45° 斜下刀", "45° ramp"),
    ("余料厚度 (mm)", "Skin (mm)"),
    ("下探深度 (mm)", "Plunge depth (mm)"),
    ("桥的宽度 (mm)", "Bridge width (mm)"),
    ("留下的桥心宽度。刀心再加两个刀半径，默认 5mm", "Width of the bridge core. The tool center adds a radius on each side. Default 5 mm"),
    ("三桥面积上限 (m²)", "Three-bridge area limit (m²)"),
    ("小于此面积的小板放 3 座桥，且在不同边", "Parts under this area get 3 bridges, on different edges"),
    ("两桥 / 大板起点 (m²)", "Two bridges / large-part start (m²)"),
    ("介于两数之间放 2 座；大于此面积算大板，不主动布", "Between the two numbers, place 2. Above the larger number the part is large and is not bridged automatically"),
    ("条子长宽比", "Strip aspect"),
    ("长/宽大于此值算长条。默认 12", "Length / width above this is a strip. Default 12"),
    ("点外形刀路轨迹放桥；窄缝自动成对。再点退出", "Click the profile path to place a bridge. A narrow gap is paired. Click again to leave"),
    ("点已有桥删除；成对一起去掉。与手动模式不能同时开", "Click a bridge to delete it. A pair goes together. Cannot be on with manual mode"),
    ("当前大板：先小板长条，再纯长条，再补小板", "This sheet: small strips, then plain strips, then the other small parts"),
    ("所有大板上每一块板都按自动规则布桥；缺刀路会先算全部", "Bridge every part on every sheet. If a toolpath is missing, calculate all sheets first"),
    ("去掉当前板所有桥，其它页保留", "Remove bridges on this sheet. Keep the other sheets"),
    ("大刀最短边 (mm)", "Large-tool minimum side (mm)"),
    ("短边 ≥ 此值用 T2 Ø10；更窄且还能进 Ø6.35 用 T1。铰链孔 / 铰杯一律 T2。", "Short side at or above this uses T2 Ø10. Narrower, if Ø6.35 still fits, uses T1. Hinge holes and cups always use T2."),
    ("按短边自动选刀，不选手动刀号。槽看槽宽，口袋看外接矩形短边。直径 < 5 mm 的孔才钻孔；Ø5 及以上（含铰杯）走清底。铰杯一律 T2 Ø10。刀路默认螺旋由里向外。进给按清底 F12000，不跟半槽。", "The tool follows the short side, not a manual number. Grooves use groove width. Pockets use the short side of the box. Holes under 5 mm are drilled. Ø5 and larger, including hinge cups, are cleared. Hinge cups always use T2 Ø10. The path spirals outward. Feed is the clearance feed, not the tongue feed."),
    ("贯通下探 (mm)", "Through plunge (mm)"),
    ("只作用于通孔。盲孔深度跟特征，不在这里改。", "Through holes only. Blind-hole depth follows the feature."),
    ("最大钻孔直径 (mm)", "Max drill diameter (mm)"),
    ("小于此值才钻孔；等于或更大走清底。默认 5。钻头只钻不铣。", "Drill only below this. This size or larger is cleared. Default 5. The drill does not mill."),
    ("不选手动刀号，孔径跟钻头走。孔间 G0。盲孔深度跟 CAD。大于阈值的孔（含铰杯）走 Area Clearance。", "No manual tool number. Hole size follows the drill. G0 between holes. Blind depth follows CAD. Larger holes, including hinge cups, use Area Clearance."),
    ("探底深度 (mm)", "Cut depth (mm)"),
    ("余料分割线贯通下探。默认 -0.55。", "Through depth of the offcut line. Default −0.55."),
    ("Ctrl 多选 · Shift 连选", "Ctrl multi-select · Shift range"),
    ("导出当前大板", "Export this sheet"),
    ("导出当前板材种类", "Export this material"),
    ("导出选中文件同一板材种类的全部大板，例如全部 15mm 匣体", "Export every sheet of the selected material, for example every 15 mm carcass"),
    ("导出所有大板的程序文件与标签 BMP 到一个目录", "Export every sheet's program and label BMP into one folder"),
    ("把当前选中的大板排版写成一份 DXF，给 Carveco 演算", "Write the selected sheet's nest to one DXF for Carveco"),
    ("同一板材种类的每张大板各一份 DXF", "One DXF for each sheet of that material"),
    ("这份工程要再切的板，和手上还能用的余料。待补件可从密排页右键加入，或在这里创建板件、选一块参照板画出新外形。补切先排余料，放不下再问要不要开整板。", "Parts to cut again, and offcuts you still have. Add a recut part from the nest's right-click menu, or create a part here from a reference part. Recut uses offcuts first, and asks before opening a full sheet."),
    ("只排待补件：先用余料，放不下再问要不要加整板。原方案的密排、刀路、导出会先暂存", "Nest recut parts only: offcuts first, then ask before a full sheet. The package nest, toolpath, and export are set aside"),
    ("待补件和余料都跟这份工程一起保存。", "Recut parts and offcuts are saved with this project."),
    ("补板库跟工程走。打开方案后，可在这里「创建板件」画出新外形，或在密排页右键「加入待补件」，也可以把还没切的整张大板「加入余料」。", "The recut library stays with the project. After you open a package, create a part here, right-click Add recut part on the nest, or add a sheet that has not been cut as an offcut."),
    ("选方案里的一块板作为材料参照，在空白画布上画出新外形，加入待补件。原方案不动。", "Pick a part as the material reference, draw a new outline, and add a recut part. The package stays as it is."),
    ("还没有待补件。点「创建板件」选一块参照板画出新外形，或在密排页右键「加入待补件」。", "No recut parts yet. Click Create part and draw from a reference part, or right-click Add recut part on the nest."),
    ("按宽×长添加一块矩形余料", "Add a rectangular offcut from width × length"),
    ("打开画板，画直角余料外形（L / 台阶）。材料跟左边下拉。", "Draw a right-angle offcut (L or step). Material follows the list on the left."),
    ("还没有余料。手填矩形，或「画余料」画 L / 台阶，或在密排页右键「本张大板加入余料」。", "No offcuts yet. Type a rectangle, draw an L or step, or right-click Add this sheet as an offcut."),
    ("后置机型目录。选中后用于 Nest / NC 输出。", "Machines and posts. The selection is used for nest and NC."),
    ("生产路线 = 载入→板材设备→密排→刀路加工档→导出。下列为当前作业进度与机型工序开关。", "Route: load, material, nest, toolpath, export. Below is this job's progress and the machine's switches."),
    ("工序开关（当前机型）", "Operation switches (this machine)"),
    ("半槽 T1（插 tongue）", "Tongue T1"),
    ("外形两刀 T2", "Two profile passes T2"),
    ("车间材料库 + 当前方案板材。库持久化到 %LocalAppData%/CabinetNC/library.json。", "Shop materials and this package. The library is saved to %LocalAppData%/CabinetNC/library.json."),
    ("刀具库与进给模板。可按机型生成默认刀，并查看当前作业工序。", "Tool library and feeds. Build the machine's default tools and see this job's operations."),
    ("排版默认值与车间偏好。保存后写入 library.json；可一键应用到当前生产加工。", "Nest defaults and shop preferences. Save writes library.json. You can apply them to the current job."),
    ("导出的标签 BMP 必须直接放在贴标软件的「Print picture path」目录里（不能有子目录）。这里填机床电脑上的那个目录，导出提示会照此显示。", "Label BMPs must sit directly in the label software Print picture path, with no subfolder. Enter that folder on the machine PC. The export message shows it."),
    ("机床标签图片目录", "Machine label-picture folder"),
    ("现场默认 D:\\CNC（2026-08-19 事故复盘确认）", "Shop default D:\\CNC (confirmed 2026-08-19)"),
    ("OSAI 单文件后置：Z0 = 板底 / 垫板上表面，安全高 30，留皮 0.5，穿透 −0.55，每把刀 M6 自动换刀。这些数值在「4 刀路与加工档」右侧可按作业调整。", "OSAI single-file post: Z0 is the board bottom / spoilboard top, safe Z 30, skin 0.5, through −0.55, M6 for each tool. Change these per job on step 4."),
    ("每种板材单独设大板尺寸。Use leftover 后填余料 X/Y，密排第一张是这块余料（贴原点）；大板边距只落在仍是外沿的边，锯开的边不加边距。", "Set the sheet size per material. With Use leftover, enter offcut X/Y. The first nest sheet is that offcut, against the origin. Sheet margin is only on edges that are still outer edges."),
    ("初始密排 →", "First nest →"),
    ("补切密排 →", "Recut nest →"),
    ("重新补切密排 →", "Recut nest again →"),
    ("按当前各板材尺寸生成第一版密排，然后自动进入「3 密排」微调", "Build the first nest from the current sizes, then open step 3 to nudge"),
    ("Fusion 设定板件木纹；这里设大板纹理方向。无纹理则不强制对齐。", "Fusion sets part grain. Set the sheet grain here. With no grain, nothing is forced into line."),
    ("允许 parts in part", "Allow parts in part"),
    ("零件嵌套进另一零件的空洞（引擎预留；勾选后写入本材料密排参数）", "Place a part in another part's opening (reserved in the engine; stored on this material when checked)"),
    ("打开后填余料 X/Y。密排第一张用这块余料，默认贴原点；放不下再开整张大板。", "When on, enter offcut X/Y. The first sheet is that offcut, against the origin. If it does not fit, a full sheet is opened."),
    ("余料 X mm", "Offcut X mm"),
    ("余料 Y mm", "Offcut Y mm"),
    ("用右侧参数对全部大板重新排版；已锁定的摆位保留", "Nest every sheet again from the settings on the right. Locked placements stay"),
    ("二次整理当前大板：只把特别窄的条子（短边小于约 100mm）从宽度边缘整列调到中间。150mm 宽的竖条贴边没问题，不动。", "Tidy this sheet: only very narrow strips (short side under about 100 mm) move from the width edge to the middle. A 150 mm vertical strip on the edge stays."),
    ("余料间隙 mm", "Offcut gap mm"),
    ("最短边 mm", "Minimum side mm"),
    ("按当前大板排版 AABB 外间隙生成余料：优先方料，拆开会短于最短边则保留 L", "Build offcuts from the gap outside this sheet's nest box. Prefer a rectangle. If a split would be shorter than the minimum side, keep the L"),
    ("按同样规则给每张已排大板生成余料线", "Build offcut lines for every nested sheet with the same rules"),
    ("下列为兼容旧逻辑的全局默认值；正式排版以「板材与设备」各材料为准。", "Old global defaults. The real nest uses each material on Material & machine."),
    ("尺寸 / 间距 / 边距以「板材与设备」各材料种类为准。", "Size, gap, and margin come from each material on Material & machine."),
    ("CabinetNC Cut · 板式家具切割站（排版 · 刀路 · OSAI 后置 · 贴标）", "CabinetNC Cut · panel furniture (nest · toolpath · OSAI post · labels)"),
    ("构建信息（上机记录请抄这一段）", "Build info (copy this into the shop log)"),
    ("docs/sprint/SHOP_LOG.md 每条记录都需要 SHA。", "Every shop-log record needs the SHA."),
    ("(未嵌入)", "(not embedded)"),
    ("模型空间 · 毫米 · 滚轮缩放 · 中键平移", "Model space · mm · wheel zoom · middle-button pan"),
    ("画线 (L) · 左边先选 Profile / Feature / 辅助线，再画。Feature 问深度；Profile 闭合换轮廓、开链切角；辅助线不进刀路", "Line (L) · pick Profile, Feature, or Guide on the left, then draw. Feature asks depth. A closed Profile replaces the outline; an open one cuts a notch. Guides are not cut"),
    ("修剪 (TR) · 选切割边（Enter=全部+外框）→ 点要剪掉的槽段或外框边", "Trim (TR) · select cutting edges (Enter = all + outline) → click the groove or outline edge to remove"),
    ("延伸槽 (EX) · 选边界（Enter=全部+外框）→ 点要延长的槽端", "Extend (EX) · select boundaries (Enter = all + outline) → click the groove end to extend"),
    ("选择 · 点选 / 框选（左→右全包，右→左相交）· Shift 增减", "Select · click / window (left→right encloses, right→left crosses) · Shift adds or removes"),
    ("移动 (M) · 选对象 → 基点 → 第二点 / @dx,dy", "Move (M) · select → base point → second point / @dx,dy"),
    ("复制 (CO) · 选对象 → 基点 → 第二点，可连续复制", "Copy (CO) · select → base point → second point, and you can copy again"),
    ("删除选中的特征 (E / Delete)", "Delete the selected feature (E / Delete)"),
    ("撤销上一步 (U / Ctrl+Z)", "Undo (U / Ctrl+Z)"),
    ("重做 (Ctrl+Y)", "Redo (Ctrl+Y)"),
    ("把整块板放进视图 (Z)", "Fit the part (Z)"),
    ("外框不可选 · 通孔可改但写回后需重排", "The outline cannot be selected · through holes can change, then the nest must be rebuilt"),
    ("Line (L) · 连续画线；拖动时 Tab 输入相对 ΔX/ΔY 并锁定", "Line (L) · draw a chain; Tab while dragging types relative ΔX/ΔY and locks it"),
    ("Rectangle (REC) · 左键画矩形；右键切换角点/中心", "Rectangle (REC) · left button draws; right button switches corner / center"),
    ("Circle (CIRCLE) · 默认圆心到边上；右键切边上到边上", "Circle · center to edge by default; right button switches to edge to edge"),
    ("网格捕捉 (F9)", "Grid snap (F9)"),
    ("正交 90° (F8)", "Ortho 90° (F8)"),
    ("命令:", "Command:"),
    ("Profile · 板件本体 / 外框", "Profile · part body / outline"),
    ("Feature · 不切透的槽 / 口袋 / 孔", "Feature · groove, pocket, or hole that does not go through"),
    ("辅助线 · 只作参考，不进刀路。右键可删除全部。", "Guide · reference only, not cut. Right-click to delete all."),
    ("画布是空的。材料跟这块板，画出新外形后加入待补件。原方案不动。", "The canvas is empty. Material follows this part. Draw a new outline and add a recut part. The package stays."),
    ("这里是已经传到云端的工程。上传会带上当前工程，以及算好的新代开料包。", "Projects already in the cloud. Upload sends this project and the Syntec cut package."),
    ("手动模式中", "Manual mode on"),
    ("清除已选桥", "Clear selected bridges"),
    ("已放", "Placed"),
    ("（成对", "(paired"),
    ("共", "total"),
    ("剩", "left"),
    ("Z0=板底", "Z0 = board bottom"),
    ("Z0=板面", "Z0 = board face"),
    ("清底+外形", "clearance + profile"),
    ("机型默认", "machine default"),
    (" · 校验通过", " · check passed"),
    ("交叉", "cross"),
    ("窗口", "window"),
    ("隐藏", "Hide"),
    ("已载入", "Loaded"),
    ("未载入", "Not loaded"),
    ("半槽", "Tongue"),
    ("外形", "Profile"),
    ("清底", "Clearance"),
    ("孔", "Holes"),
    ("槽", "Grooves"),
    ("口袋", "Pockets"),
    ("开窗", "Cutouts"),
    ("无", "None"),
    ("其他", "Other"),
    ("其它", "Other"),
    ("方案", "Package"),
    ("工程", "Project"),
    ("板件", "Part"),
    ("大板", "Sheet"),
    ("密排", "Nest"),
    ("刀路", "Toolpath"),
    ("导出", "Export"),
    ("载入", "Load"),
    ("余料", "Offcut"),
    ("预检", "Preflight"),
    ("就绪", "Ready"),
    ("更多", "More"),
    ("关闭", "Close"),
    ("取消", "Cancel"),
    ("确定", "OK"),
    ("[锁]", "[Lock]"),
    ("锁", "Lock"),
]

PUNCT = {
    "，": ", ",
    "。": ". ",
    "：": ": ",
    "；": "; ",
    "？": "?",
    "！": "!",
    "、": ", ",
    "（": " (",
    "）": ")",
    "「": ' "',
    "」": '"',
    "『": ' "',
    "』": '"',
    "《": '"',
    "》": '"',
    "—": " — ",
    "～": "~",
    "　": " ",
}


def is_cjk(ch: str) -> bool:
    o = ord(ch)
    return 0x4E00 <= o <= 0x9FFF


def build_index(terms):
    buckets = {}
    for zh, en in terms:
        buckets.setdefault(zh[0], []).append((zh, en))
    for k in buckets:
        buckets[k].sort(key=lambda p: len(p[0]), reverse=True)
    return buckets


def translate(s: str, exact, buckets) -> str:
    if s in exact:
        return exact[s]
    out = []
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if ch in PUNCT and (i + 1 >= n or s[i:i + 2] not in exact):
            # punctuation, unless a longer term starts here
            hit = None
            if is_cjk(ch) or ch in buckets:
                pass
            else:
                piece = PUNCT[ch]
                if piece == " (" and not out:
                    piece = "("
                out.append(piece)
                i += 1
                continue
        bucket = buckets.get(ch)
        hit = None
        if bucket:
            for zh, en in bucket:
                if s.startswith(zh, i):
                    hit = (zh, en)
                    break
        if hit:
            en = hit[1]
            if en and out:
                prev = out[-1][-1] if out[-1] else ""
                if prev.isalnum() and en[0].isalnum():
                    out.append(" ")
            if en:
                out.append(en)
            i += len(hit[0])
            continue
        if ch in PUNCT:
            piece = PUNCT[ch]
            if piece == " (" and not out:
                piece = "("
            out.append(piece)
            i += 1
            continue
        out.append(ch)
        i += 1
    text = "".join(out)
    text = text.replace("  ", " ")
    while "  " in text:
        text = text.replace("  ", " ")
    return text


def csharp_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'


def main():
    # Drop duplicate keys, keep the first (more specific lists are earlier).
    chars = {
        "一": "one", "三": "three", "且": "and", "两": "two", "主": "main", "义": "",
        "二": "two", "于": "at", "些": "some", "交": "cross", "仅": "only", "仍": "still",
        "仓": "bin", "优": "better", "传": "send", "位": "place", "住": "stay", "体": "body",
        "何": "what", "作": "make", "使": "use", "侧": "side", "保": "keep", "修": "repair",
        "写": "write", "准": "exact", "几": "a few", "凸": "bump", "凹": "notch", "分": "part",
        "划": "mark", "列": "column", "判": "judge", "别": "other", "制": "make", "剪": "trim",
        "割": "cut", "动": "move", "助": "help", "勾": "tick", "化": "", "即": "that is",
        "原": "original", "参": "param", "友": "", "双": "double", "反": "back", "取": "take",
        "变": "change", "叠": "stack", "另": "another", "台": "table", "合": "join", "同": "same",
        "含": "including", "启": "start", "命": "command", "响": "", "哪": "which", "善": "better",
        "围": "enclose", "图": "drawing", "址": "address", "坏": "bad", "型": "type", "填": "fill",
        "增": "add", "备": "", "复": "again", "多": "more", "夹": "clip", "套": "set", "好": "ok",
        "妲": "groove", "字": "name", "它": "it", "完": "done", "定": "set", "容": "allow",
        "屿": "", "岛": "", "工": "work", "差": "short", "布": "place", "带": "with", "常": "often",
        "序": "order", "应": "should", "度": "deg", "座": "", "延": "extend", "异": "odd",
        "弃": "discard", "弧": "arc", "强": "force", "归": "classed as", "录": "record", "待": "pending",
        "律": "", "微": "", "心": "center", "慢": "slow", "成": "into", "所": "", "手": "hand",
        "才": "only", "打": "", "扫": "sweep", "找": "find", "拒": "reject", "持": "keep",
        "换": "switch", "掠": "", "提": "", "插": "insert", "撞": "hit", "操": "", "支": "",
        "收": "collect", "数": "count", "整": "whole", "断": "break", "时": "when", "明": "",
        "易": "", "暂": "for now", "替": "instead", "最": "most", "机": "machine", "杈": "edge",
        "杯": "cup", "析": "", "柄": "handle", "查": "check", "标": "mark", "栏": "column",
        "核": "check", "格": "", "框": "frame", "橙": "orange", "止": "stop", "正": "",
        "残": "left", "比": "than", "沿": "along", "混": "mix", "清": "clear", "满": "full",
        "瀛": "hole", "灯": "", "片": "", "版": "version", "独": "alone", "现": "now", "由": "by",
        "画": "draw", "界": "boundary", "留": "leave", "白": "white", "盲": "blind", "相": "",
        "知": "", "确": "confirm", "碰": "touch", "示": "show", "禁": "blocked", "离": "away",
        "移": "move", "程": "", "穿": "through", "窄": "narrow", "立": "", "竖": "vertical",
        "简": "simple", "算": "calculate", "红": "red", "纯": "plain", "细": "thin", "绝": "",
        "缺": "missing", "置": "place", "考": "", "腔": "", "自": "self", "色": "color",
        "落": "land", "蓝": "blue", "薄": "thin", "行": "row", "补": "recut", "表": "table",
        "被": "", "见": "see", "解": "", "计": "", "认": "", "记": "record", "识": "",
        "读": "read", "调": "adjust", "贴": "label", "起": "from", "超": "over", "足": "enough",
        "距": "distance", "跟": "follow", "跳": "skip", "车": "", "转": "turn", "软": "",
        "较": "", "辅": "guide", "运": "move", "近": "near", "这": "this", "连": "and",
        "退": "back", "适": "fit", "透": "through", "通": "through", "遇": "", "邻": "neighbor",
        "里": "in", "重": "again", "量": "amount", "针": "", "钻": "drill", "铣": "mill",
        "镂": "cutout", "器": "", "黑": "black", "问": "ask", "间": "between", "阻": "block", "附": "", "降": "lower",
        "陷": "", "随": "with", "雅": "", "顺": "along", "须": "must",
    }
    seen = set()
    terms = []
    for zh, en in list(TERMS) + list(chars.items()):
        if not zh or zh in seen:
            continue
        seen.add(zh)
        terms.append((zh, en))
    buckets = build_index(terms)
    root = Path(r"c:\Users\azqrv\Documents\cabinetnc-cut\dotnet\src")
    import re
    runs = set()
    cjk = re.compile(r"[\u4e00-\u9fff]+")
    for d in ["CabinetNC.Desktop", "CabinetNC.Desktop.Core", "CabinetNC.Domain", "CabinetNC.Verify"]:
        for p in (root / d).rglob("*"):
            if p.suffix not in {".cs", ".xaml"}:
                continue
            if p.name.endswith(".g.cs"):
                continue
            if any(x in p.parts for x in ("obj", "bin")):
                continue
            text = p.read_text(encoding="utf-8")
            if p.suffix == ".cs":
                text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
                text = re.sub(r"//.*?$", "", text, flags=re.M)
            runs.update(cjk.findall(text))
    leftover = []
    for run in sorted(runs, key=len, reverse=True):
        en = translate(run, EXACT, buckets)
        if cjk.search(en):
            leftover.append((run, en))
    gap_path = Path(r"c:\Users\azqrv\Documents\cabinetnc-cut\dotnet\tools\_leftover.txt")
    gap_path.write_text(
        "\n".join(f"{run}\t=>\t{en}" for run, en in leftover),
        encoding="utf-8",
    )
    print(f"runs={len(runs)} leftover={len(leftover)} terms={len(terms)}")

    lines = [
        "// Generated by dotnet/tools/_gen_lexicon.py. Do not edit by hand.",
        "namespace CabinetNC.Desktop.Core;",
        "",
        "static class UiLexicon",
        "{",
        "    public static readonly Dictionary<string, string> Exact = new()",
        "    {",
    ]
    for zh, en in EXACT.items():
        lines.append(f"        [{csharp_string(zh)}] = {csharp_string(en)},")
    lines += [
        "    };",
        "",
        "    public static readonly (string Zh, string En)[] Terms =",
        "    [",
    ]
    for zh, en in terms:
        lines.append(f"        ({csharp_string(zh)}, {csharp_string(en)}),")
    lines += [
        "    ];",
        "}",
        "",
    ]
    out = Path(r"c:\Users\azqrv\Documents\cabinetnc-cut\dotnet\src\CabinetNC.Desktop.Core\UiLexicon.g.cs")
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out, "leftover", len(leftover))


if __name__ == "__main__":
    main()
